import type {
  AnalyticsOverviewMetrics,
  PlatformPerformance,
  TopPost,
  ActivityTimelineItem,
  QuickInsight,
} from "@/lib/zod-schemas/analytics/overview";

export const mockAnalyticsOverviewMetrics: AnalyticsOverviewMetrics = {
  totalEngagement: 45678,
  totalReach: 234567,
  followerGrowth: 1234,
  engagementRate: 4.8,
  postsPublished: 42,
  avgResponseTime: 1800, // 30 minutes
  csatScore: 4.5,
  socialPerformanceScore: 82,

  // Trends
  engagementTrend: 12.5,
  reachTrend: 8.3,
  followerGrowthTrend: 15.2,
  engagementRateTrend: 3.1,
};

export const mockPlatformPerformance: PlatformPerformance[] = [
  {
    platform: "instagram",
    name: "Instagram",
    followerCount: 45678,
    growthPercentage: 12.5,
    engagementRate: 5.2,
    topPostEngagement: 3456,
  },
  {
    platform: "facebook",
    name: "Facebook",
    followerCount: 89012,
    growthPercentage: 8.3,
    engagementRate: 3.8,
    topPostEngagement: 2145,
  },
  {
    platform: "x",
    name: "X (Twitter)",
    followerCount: 34567,
    growthPercentage: 15.7,
    engagementRate: 4.5,
    topPostEngagement: 1897,
  },
  {
    platform: "linkedin",
    name: "LinkedIn",
    followerCount: 23456,
    growthPercentage: 22.1,
    engagementRate: 6.3,
    topPostEngagement: 1542,
  },
  {
    platform: "tiktok",
    name: "TikTok",
    followerCount: 67890,
    growthPercentage: 45.2,
    engagementRate: 8.9,
    topPostEngagement: 5678,
  },
  {
    platform: "youtube",
    name: "YouTube",
    followerCount: 12345,
    growthPercentage: 5.4,
    engagementRate: 7.1,
    topPostEngagement: 987,
  },
];

export const mockTopPosts: TopPost[] = [
  {
    id: "top-post-1",
    content: "Excited to announce our new product launch! 🚀 This has been months in the making...",
    thumbnail: "https://picsum.photos/seed/post1/400/300",
    platform: "instagram",
    platforms: ["instagram", "facebook", "x"],
    publishedAt: new Date("2024-11-20T10:30:00"),
    engagement: 5678,
    reach: 45678,
    engagementRate: 12.4,
  },
  {
    id: "top-post-2",
    content: "Behind the scenes of our latest campaign shoot 📸 Swipe to see the team in action!",
    thumbnail: "https://picsum.photos/seed/post2/400/300",
    platform: "instagram",
    platforms: ["instagram"],
    publishedAt: new Date("2024-11-19T14:15:00"),
    engagement: 4523,
    reach: 38901,
    engagementRate: 11.6,
  },
  {
    id: "top-post-3",
    content: "Quick tips for maximizing productivity in 2024 🎯 Thread 🧵",
    platform: "x",
    platforms: ["x", "linkedin"],
    publishedAt: new Date("2024-11-18T09:45:00"),
    engagement: 3456,
    reach: 28765,
    engagementRate: 12.0,
  },
  {
    id: "top-post-4",
    content: "Customer success story: How @CompanyXYZ increased efficiency by 300%",
    thumbnail: "https://picsum.photos/seed/post4/400/300",
    platform: "linkedin",
    platforms: ["linkedin", "facebook"],
    publishedAt: new Date("2024-11-17T11:20:00"),
    engagement: 2987,
    reach: 25432,
    engagementRate: 11.7,
  },
  {
    id: "top-post-5",
    content: "New video: 5 mistakes you're making with social media marketing",
    thumbnail: "https://picsum.photos/seed/post5/400/300",
    platform: "youtube",
    platforms: ["youtube", "tiktok"],
    publishedAt: new Date("2024-11-16T16:00:00"),
    engagement: 2654,
    reach: 23456,
    engagementRate: 11.3,
  },
  {
    id: "top-post-6",
    content: "Weekend vibes ✨ What are you working on this weekend?",
    thumbnail: "https://picsum.photos/seed/post6/400/300",
    platform: "instagram",
    platforms: ["instagram", "facebook"],
    publishedAt: new Date("2024-11-15T13:30:00"),
    engagement: 2341,
    reach: 21234,
    engagementRate: 11.0,
  },
];

export const mockActivityTimeline: ActivityTimelineItem[] = [
  {
    id: "activity-1",
    type: "milestone",
    title: "Reached 50K Instagram followers",
    description: "Your Instagram account just hit a major milestone!",
    timestamp: new Date("2024-11-22T15:45:00"),
    severity: "success",
  },
  {
    id: "activity-2",
    type: "achievement",
    title: "Post went viral",
    description: "Your latest post on TikTok reached 100K views in 24 hours",
    timestamp: new Date("2024-11-22T10:20:00"),
    severity: "success",
  },
  {
    id: "activity-3",
    type: "alert",
    title: "Response time increasing",
    description: "Average response time is 15% higher than last week",
    timestamp: new Date("2024-11-22T08:15:00"),
    severity: "warning",
  },
  {
    id: "activity-4",
    type: "achievement",
    title: "Best engagement rate this month",
    description: "Your LinkedIn engagement rate hit an all-time high of 8.2%",
    timestamp: new Date("2024-11-21T16:30:00"),
    severity: "success",
  },
  {
    id: "activity-5",
    type: "milestone",
    title: "1000th post published",
    description: "Congratulations on publishing your 1000th post!",
    timestamp: new Date("2024-11-21T14:00:00"),
    severity: "info",
  },
  {
    id: "activity-6",
    type: "warning",
    title: "Follower growth slowing",
    description: "Facebook follower growth is down 20% from last month",
    timestamp: new Date("2024-11-21T09:45:00"),
    severity: "warning",
  },
];

export const mockQuickInsights: QuickInsight[] = [
  {
    id: "insight-1",
    category: "working",
    message: "TikTok engagement rate is 45% higher than average - keep posting video content!",
    impact: "high",
    actionable: true,
    actionLabel: "View TikTok analytics",
  },
  {
    id: "insight-2",
    category: "working",
    message: "LinkedIn posts on Tuesday mornings get 2x more engagement",
    impact: "high",
    actionable: true,
    actionLabel: "Schedule more Tuesday posts",
  },
  {
    id: "insight-3",
    category: "attention",
    message: "Instagram Stories completion rate dropped to 45% (was 68% last month)",
    impact: "medium",
    actionable: true,
    actionLabel: "Analyze story performance",
  },
  {
    id: "insight-4",
    category: "attention",
    message: "Response times are 30% slower than target - consider adding team members",
    impact: "high",
    actionable: true,
    actionLabel: "View inbox analytics",
  },
  {
    id: "insight-5",
    category: "opportunity",
    message: "Competitor analysis shows trending hashtag #Innovation2024 with high engagement",
    impact: "medium",
    actionable: true,
    actionLabel: "Use in next post",
  },
  {
    id: "insight-6",
    category: "opportunity",
    message: "Your audience is most active between 7-9 PM - consider scheduling posts then",
    impact: "medium",
    actionable: true,
    actionLabel: "Optimize posting schedule",
  },
];
