import type {
  RSSFeed,
  RSSFeedItem,
  EvergreenContent,
  ContentQueue,
  ContentQueueItem,
  ListeningStream,
  ListeningStreamItem,
  ListeningAlert,
  ScheduledReport,
  PerformanceAlert,
  ApprovalWorkflow,
  ApprovalRequest,
  Approval,
} from "../zod-schemas";

// ============================================================================
// RSS FEEDS
// ============================================================================

export const mockRSSFeeds: RSSFeed[] = [
  {
    id: "rss-1",
    workspaceId: "workspace-1",
    name: "Company Blog",
    feedUrl: "https://blog.company.com/feed",
    description: "Main company blog RSS feed",
    autoPublish: true,
    targetPlatforms: ["twitter", "linkedin"],
    postTemplate: "{title}\n\n{description}\n\nRead more: {link}",
    checkIntervalMinutes: 60,
    lastCheckedAt: "2025-11-22T11:00:00Z",
    lastPublishedAt: "2025-11-21T15:30:00Z",
    keywordFilters: ["product", "announcement", "guide"],
    maxPostsPerDay: 3,
    isActive: true,
    healthStatus: "healthy",
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-11-22T11:00:00Z",
  },
  {
    id: "rss-2",
    workspaceId: "workspace-1",
    name: "Industry News",
    feedUrl: "https://industry-news.com/feed",
    description: "Curated industry news feed",
    autoPublish: false,
    targetPlatforms: ["twitter"],
    postTemplate: "📰 {title}\n\n{link}\n\n#Industry #News",
    checkIntervalMinutes: 30,
    lastCheckedAt: "2025-11-22T11:30:00Z",
    excludeKeywords: ["competitor", "lawsuit"],
    isActive: true,
    healthStatus: "healthy",
    createdBy: "user-2",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-11-22T11:30:00Z",
  },
];

export const mockRSSFeedItems: RSSFeedItem[] = [
  {
    id: "rss-item-1",
    feedId: "rss-1",
    workspaceId: "workspace-1",
    guid: "blog-post-123",
    title: "Introducing Our New Product Features",
    link: "https://blog.company.com/new-features",
    description: "We're excited to announce several new features that will help you...",
    author: "Sarah Johnson",
    categories: ["product", "announcement"],
    publishedAt: "2025-11-21T15:00:00Z",
    wasPublished: true,
    postId: "post-123",
    publishedToPlatforms: ["twitter", "linkedin"],
    matchedFilters: ["product", "announcement"],
    metadata: {},
    discoveredAt: "2025-11-21T15:15:00Z",
  },
  {
    id: "rss-item-2",
    feedId: "rss-1",
    workspaceId: "workspace-1",
    guid: "blog-post-124",
    title: "Ultimate Guide to Social Media Marketing",
    link: "https://blog.company.com/smm-guide",
    description: "A comprehensive guide covering everything you need to know...",
    author: "Mike Chen",
    categories: ["guide", "marketing"],
    publishedAt: "2025-11-22T10:00:00Z",
    wasPublished: false,
    publishedToPlatforms: [],
    matchedFilters: ["guide"],
    metadata: {},
    discoveredAt: "2025-11-22T11:00:00Z",
  },
];

// ============================================================================
// EVERGREEN CONTENT
// ============================================================================

export const mockEvergreenContent: EvergreenContent[] = [
  {
    id: "evergreen-1",
    workspaceId: "workspace-1",
    title: "5 Tips for Better Social Media Engagement",
    content: "Want to boost your social media engagement? Here are 5 proven tips:\n\n1. Post consistently\n2. Use eye-catching visuals\n3. Engage with your audience\n4. Use relevant hashtags\n5. Post at optimal times",
    mediaAssetIds: ["media-1"],
    platforms: ["twitter", "linkedin", "facebook"],
    platformVariations: {
      twitter: {
        content: "🚀 5 Tips to Boost Your Social Media Engagement:\n\n✅ Post consistently\n✅ Use visuals\n✅ Engage authentically\n✅ Use hashtags\n✅ Time it right\n\nWhich tip do you find most effective? 👇",
        hashtags: ["#SocialMedia", "#Marketing"],
      },
    },
    recycleIntervalDays: 30,
    lastPostedAt: "2025-10-22T09:00:00Z",
    nextPostAt: "2025-11-21T09:00:00Z",
    timesPosted: 4,
    maxReposts: 12,
    totalEngagement: 2450,
    avgEngagementRate: 0.0425,
    categories: ["tips", "engagement"],
    tags: ["evergreen", "educational"],
    isActive: true,
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-10-22T09:00:00Z",
  },
  {
    id: "evergreen-2",
    workspaceId: "workspace-1",
    title: "Our Company Values",
    content: "At our company, we believe in:\n\n💙 Putting customers first\n🌟 Innovation and creativity\n🤝 Collaboration and teamwork\n🌱 Continuous growth and learning\n\nThese values guide everything we do.",
    mediaAssetIds: [],
    platforms: ["linkedin", "facebook"],
    platformVariations: {},
    recycleIntervalDays: 60,
    lastPostedAt: "2025-09-15T14:00:00Z",
    nextPostAt: "2025-11-14T14:00:00Z",
    timesPosted: 2,
    totalEngagement: 890,
    avgEngagementRate: 0.0325,
    categories: ["company culture"],
    tags: ["evergreen", "values"],
    isActive: true,
    createdBy: "user-2",
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-09-15T14:00:00Z",
  },
];

// ============================================================================
// CONTENT QUEUES
// ============================================================================

export const mockContentQueues: ContentQueue[] = [
  {
    id: "queue-1",
    workspaceId: "workspace-1",
    name: "Daily Content Queue",
    description: "Main content queue for daily posts",
    color: "#3b82f6",
    platforms: ["twitter", "facebook", "instagram"],
    scheduleType: "time_slots",
    scheduleConfig: {
      timeSlots: ["09:00", "13:00", "17:00"],
    },
    timezone: "America/New_York",
    postsPerDay: 3,
    shufflePosts: false,
    skipWeekends: false,
    skipHolidays: true,
    autoFillEnabled: true,
    autoFillSources: ["evergreen:evergreen-1", "rss:rss-1"],
    isActive: true,
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-11-22T09:00:00Z",
  },
  {
    id: "queue-2",
    workspaceId: "workspace-1",
    name: "LinkedIn Professional Content",
    description: "Professional content for LinkedIn",
    color: "#0a66c2",
    platforms: ["linkedin"],
    scheduleType: "optimal",
    scheduleConfig: {
      useCalculatedTimes: true,
      fallback: "09:00",
      minScore: 70,
    },
    timezone: "UTC",
    postsPerDay: 1,
    shufflePosts: true,
    skipWeekends: true,
    skipHolidays: true,
    autoFillEnabled: false,
    isActive: true,
    createdBy: "user-2",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-11-15T10:00:00Z",
  },
];

export const mockContentQueueItems: ContentQueueItem[] = [
  {
    id: "queue-item-1",
    queueId: "queue-1",
    postId: "post-1",
    workspaceId: "workspace-1",
    position: 1,
    status: "scheduled",
    scheduledFor: "2025-11-23T09:00:00Z",
    retryCount: 0,
    metadata: {},
    addedAt: "2025-11-20T10:00:00Z",
    updatedAt: "2025-11-22T09:00:00Z",
  },
  {
    id: "queue-item-2",
    queueId: "queue-1",
    postId: "post-2",
    workspaceId: "workspace-1",
    position: 2,
    status: "pending",
    retryCount: 0,
    metadata: {},
    addedAt: "2025-11-21T10:00:00Z",
    updatedAt: "2025-11-21T10:00:00Z",
  },
  {
    id: "queue-item-3",
    queueId: "queue-1",
    postId: "post-3",
    workspaceId: "workspace-1",
    position: 3,
    status: "published",
    scheduledFor: "2025-11-22T09:00:00Z",
    publishedAt: "2025-11-22T09:00:15Z",
    publicationIds: ["pub-1", "pub-2"],
    retryCount: 0,
    metadata: {},
    addedAt: "2025-11-19T10:00:00Z",
    updatedAt: "2025-11-22T09:00:15Z",
  },
];

// ============================================================================
// LISTENING STREAMS
// ============================================================================

export const mockListeningStreams: ListeningStream[] = [
  {
    id: "stream-1",
    workspaceId: "workspace-1",
    name: "Brand Mentions",
    description: "Monitor all mentions of our brand across social platforms",
    streamType: "brand_mentions",
    color: "#10b981",
    searchConfig: {
      keywords: ["@ourcompany", "#ourcompany", "our company"],
      exactMatch: false,
      excludeKeywords: ["competitor"],
    },
    platforms: ["twitter", "instagram", "facebook"],
    excludedPlatforms: [],
    alertEnabled: true,
    alertConfig: {
      threshold: { mentions: 50, timeWindowMinutes: 60 },
      sentiment: "negative",
      notifyUsers: ["user-1", "user-2"],
      notificationChannels: ["slack", "email"],
    },
    autoRefresh: true,
    refreshIntervalMinutes: 15,
    lastRefreshedAt: "2025-11-22T11:45:00Z",
    tags: ["brand", "monitoring"],
    isActive: true,
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-11-22T11:45:00Z",
  },
  {
    id: "stream-2",
    workspaceId: "workspace-1",
    name: "Competitor Activity",
    description: "Track competitor posts and engagement",
    streamType: "competitor",
    color: "#f59e0b",
    searchConfig: {
      competitorName: "Competitor Inc",
      keywords: ["@competitor", "#competitor"],
      trackProducts: true,
    },
    platforms: ["twitter", "linkedin"],
    excludedPlatforms: [],
    alertEnabled: false,
    autoRefresh: true,
    refreshIntervalMinutes: 30,
    lastRefreshedAt: "2025-11-22T11:30:00Z",
    tags: ["competitor", "research"],
    isActive: true,
    createdBy: "user-2",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-11-22T11:30:00Z",
  },
  {
    id: "stream-3",
    workspaceId: "workspace-1",
    name: "Industry Hashtags",
    description: "Monitor trending industry hashtags",
    streamType: "hashtag",
    searchConfig: {
      hashtags: ["#SocialMediaMarketing", "#SMM", "#DigitalMarketing"],
      relatedHashtags: true,
    },
    platforms: ["twitter", "instagram"],
    excludedPlatforms: [],
    alertEnabled: false,
    autoRefresh: true,
    refreshIntervalMinutes: 20,
    lastRefreshedAt: "2025-11-22T11:40:00Z",
    minEngagement: 100,
    tags: ["industry", "trends"],
    isActive: true,
    createdBy: "user-1",
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-11-22T11:40:00Z",
  },
];

export const mockListeningStreamItems: ListeningStreamItem[] = [
  {
    id: "stream-item-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "twitter",
    platformPostId: "twitter-123",
    platformUrl: "https://twitter.com/user/status/123",
    authorName: "John Doe",
    authorHandle: "@johndoe",
    authorProfileUrl: "https://twitter.com/johndoe",
    authorAvatarUrl: "https://avatar.url/johndoe.jpg",
    authorVerified: false,
    content: "Just tried @ourcompany's new feature and it's amazing! Best tool I've used for social media management. #SocialMedia",
    contentPreview: "Just tried @ourcompany's new feature and it's amazing!",
    mediaUrls: [],
    hashtags: ["#SocialMedia"],
    mentions: ["@ourcompany"],
    engagementCount: 145,
    likesCount: 120,
    commentsCount: 15,
    sharesCount: 10,
    viewsCount: 2500,
    followerCount: 5000,
    isInfluencer: false,
    sentiment: "positive",
    sentimentScore: 0.92,
    categories: ["praise"],
    matchedKeywords: ["@ourcompany"],
    isRead: true,
    isStarred: false,
    isArchived: false,
    repliedTo: true,
    convertedToConversation: false,
    postedAt: "2025-11-22T10:30:00Z",
    discoveredAt: "2025-11-22T10:32:00Z",
    metadata: {},
    createdAt: "2025-11-22T10:32:00Z",
  },
  {
    id: "stream-item-2",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "instagram",
    platformPostId: "instagram-456",
    platformUrl: "https://instagram.com/p/456",
    authorName: "Sarah Marketing",
    authorHandle: "@sarahmarketing",
    authorProfileUrl: "https://instagram.com/sarahmarketing",
    authorAvatarUrl: "https://avatar.url/sarah.jpg",
    authorVerified: true,
    content: "Love what @ourcompany is doing in the social media space! Their innovation is unmatched. 🚀",
    contentPreview: "Love what @ourcompany is doing...",
    mediaUrls: ["https://media.url/image1.jpg"],
    hashtags: [],
    mentions: ["@ourcompany"],
    engagementCount: 2340,
    likesCount: 2100,
    commentsCount: 180,
    sharesCount: 60,
    followerCount: 125000,
    isInfluencer: true,
    sentiment: "positive",
    sentimentScore: 0.88,
    categories: ["praise", "influencer"],
    matchedKeywords: ["@ourcompany"],
    isRead: false,
    isStarred: true,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T11:15:00Z",
    discoveredAt: "2025-11-22T11:17:00Z",
    metadata: {},
    createdAt: "2025-11-22T11:17:00Z",
  },
];

export const mockListeningAlerts: ListeningAlert[] = [
  {
    id: "alert-1",
    workspaceId: "workspace-1",
    streamId: "stream-1",
    alertType: "mention_spike",
    severity: "warning",
    title: "Brand Mention Spike Detected",
    description: "Unusual increase in brand mentions detected across Twitter and Instagram",
    triggerData: {
      currentCount: 65,
      threshold: 50,
      timeWindow: "1 hour",
      increasePercentage: 130,
    },
    affectedPlatforms: ["twitter", "instagram"],
    relatedStreamItemIds: ["stream-item-1", "stream-item-2"],
    notifiedUsers: ["user-1", "user-2"],
    notificationChannels: ["slack", "email"],
    notificationSentAt: "2025-11-22T11:20:00Z",
    isAcknowledged: true,
    acknowledgedBy: "user-1",
    acknowledgedAt: "2025-11-22T11:25:00Z",
    acknowledgmentNotes: "Spike related to positive product launch coverage",
    actionsTaken: [
      {
        timestamp: "2025-11-22T11:30:00Z",
        action: "Engaged with top mentions",
        userId: "user-1",
      },
    ],
    triggeredAt: "2025-11-22T11:20:00Z",
    metadata: {},
    createdAt: "2025-11-22T11:20:00Z",
  },
  {
    id: "alert-2",
    workspaceId: "workspace-1",
    streamId: "stream-1",
    alertType: "influencer_mention",
    severity: "info",
    title: "Influencer Mentioned Brand",
    description: "High-profile influencer @sarahmarketing mentioned the brand",
    triggerData: {
      influencer: "@sarahmarketing",
      followerCount: 125000,
      postUrl: "https://instagram.com/p/456",
    },
    affectedPlatforms: ["instagram"],
    relatedStreamItemIds: ["stream-item-2"],
    notifiedUsers: ["user-1", "user-2"],
    notificationChannels: ["slack"],
    notificationSentAt: "2025-11-22T11:18:00Z",
    isAcknowledged: false,
    actionsTaken: [],
    triggeredAt: "2025-11-22T11:18:00Z",
    metadata: {},
    createdAt: "2025-11-22T11:18:00Z",
  },
];

// ============================================================================
// SCHEDULED REPORTS
// ============================================================================

export const mockScheduledReports: ScheduledReport[] = [
  {
    id: "report-1",
    workspaceId: "workspace-1",
    name: "Weekly Performance Report",
    description: "Comprehensive weekly performance metrics across all platforms",
    reportType: "performance",
    reportConfig: {
      metrics: ["engagement_rate", "follower_growth", "reach", "impressions"],
      platforms: ["twitter", "instagram", "facebook", "linkedin"],
      dateRange: "last_7_days",
      includeCharts: true,
      includeComparisons: true,
      compareTo: "previous_period",
      groupBy: "platform",
    },
    scheduleCron: "0 9 * * 1",
    timezone: "America/New_York",
    recipients: ["manager@company.com", "team@company.com"],
    ccRecipients: [],
    bccRecipients: [],
    format: "pdf",
    deliveryMethod: "email",
    deliveryConfig: {
      email: {
        subjectTemplate: "Weekly Performance Report - {date_range}",
        bodyTemplate: "Please find attached your weekly performance report.",
        attachRawData: true,
      },
    },
    isActive: true,
    lastSentAt: "2025-11-18T09:00:00Z",
    nextSendAt: "2025-11-25T09:00:00Z",
    lastExecutionStatus: "completed",
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-11-18T09:00:00Z",
  },
  {
    id: "report-2",
    workspaceId: "workspace-1",
    name: "Monthly Sentiment Analysis",
    description: "Monthly sentiment analysis of brand mentions",
    reportType: "sentiment",
    reportConfig: {
      metrics: ["sentiment_score", "positive_mentions", "negative_mentions"],
      platforms: ["all"],
      dateRange: "last_month",
      includeCharts: true,
      includeWordCloud: true,
    },
    scheduleCron: "0 10 1 * *",
    timezone: "UTC",
    recipients: ["executives@company.com"],
    ccRecipients: ["marketing@company.com"],
    bccRecipients: [],
    format: "pdf",
    deliveryMethod: "email",
    deliveryConfig: {},
    isActive: true,
    lastSentAt: "2025-11-01T10:00:00Z",
    nextSendAt: "2025-12-01T10:00:00Z",
    lastExecutionStatus: "completed",
    createdBy: "user-2",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-11-01T10:00:00Z",
  },
];

// ============================================================================
// PERFORMANCE ALERTS
// ============================================================================

export const mockPerformanceAlerts: PerformanceAlert[] = [
  {
    id: "perf-alert-1",
    workspaceId: "workspace-1",
    name: "Low Engagement Rate Alert",
    description: "Alert when engagement rate drops below threshold",
    metric: "engagement_rate",
    thresholdConfig: {
      condition: "below",
      value: 2.5,
      comparisonPeriod: "previous_day",
      platforms: ["instagram", "facebook"],
      consecutiveOccurrences: 2,
    },
    checkIntervalMinutes: 60,
    lastCheckedAt: "2025-11-22T11:00:00Z",
    notifyUsers: ["user-1", "user-2"],
    notificationChannels: ["email", "slack"],
    notificationConfig: {
      email: {
        subject: "Alert: Engagement Rate Below Threshold",
        includeChart: true,
      },
    },
    isActive: true,
    lastTriggeredAt: "2025-11-20T14:00:00Z",
    triggerCount: 3,
    cooldownMinutes: 120,
    createdBy: "user-1",
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-11-20T14:00:00Z",
  },
  {
    id: "perf-alert-2",
    workspaceId: "workspace-1",
    name: "Follower Growth Milestone",
    description: "Alert when follower count reaches milestones",
    metric: "follower_count",
    thresholdConfig: {
      condition: "above",
      value: 10000,
      platforms: ["twitter"],
    },
    checkIntervalMinutes: 360,
    notifyUsers: ["user-1"],
    notificationChannels: ["email", "slack"],
    notificationConfig: {},
    isActive: true,
    triggerCount: 0,
    cooldownMinutes: 1440,
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
];

// ============================================================================
// APPROVAL WORKFLOWS
// ============================================================================

export const mockApprovalWorkflows: ApprovalWorkflow[] = [
  {
    id: "workflow-1",
    workspaceId: "workspace-1",
    name: "Standard Post Approval",
    description: "Standard two-level approval workflow for all posts",
    steps: [
      {
        level: 1,
        name: "Content Review",
        approvers: ["user-2"],
        requiredApprovals: 1,
        allowSelfApproval: false,
      },
      {
        level: 2,
        name: "Final Approval",
        approvers: ["user-1"],
        requiredApprovals: 1,
        allowSelfApproval: false,
        condition: "platforms includes 'facebook' OR platforms includes 'instagram'",
      },
    ],
    applyConditions: {
      platforms: ["facebook", "instagram"],
    },
    autoScheduleOnApproval: true,
    autoNotifyApprovers: true,
    expiryDays: 7,
    allowComments: true,
    isActive: true,
    isDefault: true,
    priority: 10,
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-03-10T10:00:00Z",
  },
  {
    id: "workflow-2",
    workspaceId: "workspace-1",
    name: "Quick Approval",
    description: "Single-level approval for Twitter posts",
    steps: [
      {
        level: 1,
        name: "Quick Review",
        approvers: ["user-2", "user-3"],
        requiredApprovals: 1,
        allowSelfApproval: false,
      },
    ],
    applyConditions: {
      platforms: ["twitter"],
      maxCharacterCount: 280,
    },
    autoScheduleOnApproval: true,
    autoNotifyApprovers: true,
    expiryDays: 3,
    allowComments: true,
    isActive: true,
    isDefault: false,
    priority: 5,
    createdBy: "user-1",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-02-01T10:00:00Z",
  },
];

export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: "request-1",
    workspaceId: "workspace-1",
    workflowId: "workflow-1",
    postId: "post-10",
    workflowSteps: [
      {
        level: 1,
        name: "Content Review",
        approvers: ["user-2"],
        requiredApprovals: 1,
      },
      {
        level: 2,
        name: "Final Approval",
        approvers: ["user-1"],
        requiredApprovals: 1,
      },
    ],
    status: "pending",
    currentLevel: 1,
    submittedBy: "user-3",
    submissionNote: "New product launch post for Facebook and Instagram",
    submittedAt: "2025-11-22T09:00:00Z",
    expiresAt: "2025-11-29T09:00:00Z",
    commentsCount: 2,
    metadata: {},
    createdAt: "2025-11-22T09:00:00Z",
    updatedAt: "2025-11-22T10:30:00Z",
  },
  {
    id: "request-2",
    workspaceId: "workspace-1",
    workflowId: "workflow-2",
    postId: "post-11",
    workflowSteps: [
      {
        level: 1,
        name: "Quick Review",
        approvers: ["user-2", "user-3"],
        requiredApprovals: 1,
      },
    ],
    status: "approved",
    currentLevel: 1,
    submittedBy: "user-4",
    submittedAt: "2025-11-21T14:00:00Z",
    resolvedAt: "2025-11-21T14:30:00Z",
    resolvedBy: "user-2",
    resolutionNote: "Approved - looks good!",
    expiresAt: "2025-11-24T14:00:00Z",
    commentsCount: 0,
    metadata: {},
    createdAt: "2025-11-21T14:00:00Z",
    updatedAt: "2025-11-21T14:30:00Z",
  },
];

export const mockApprovals: Approval[] = [
  {
    id: "approval-1",
    requestId: "request-1",
    workspaceId: "workspace-1",
    approverId: "user-2",
    level: 1,
    decision: "pending",
    notifiedAt: "2025-11-22T09:01:00Z",
    metadata: {},
    createdAt: "2025-11-22T09:01:00Z",
  },
  {
    id: "approval-2",
    requestId: "request-2",
    workspaceId: "workspace-1",
    approverId: "user-2",
    level: 1,
    decision: "approved",
    comments: "Looks great! Approved for publishing.",
    notifiedAt: "2025-11-21T14:01:00Z",
    respondedAt: "2025-11-21T14:30:00Z",
    metadata: {},
    createdAt: "2025-11-21T14:01:00Z",
  },
];
