import type { MediaFolder, MediaTag, MediaLibraryItem } from "../zod-schemas/content-library.schema";

export const mockMediaFolders: MediaFolder[] = [
  {
    id: "folder-1",
    workspace_id: "workspace-1",
    name: "Brand Assets",
    parent_folder_id: null,
    color: "#6366f1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "folder-2",
    workspace_id: "workspace-1",
    name: "Logos",
    parent_folder_id: "folder-1",
    color: null,
    created_at: new Date("2024-01-16").toISOString(),
    updated_at: new Date("2024-01-16").toISOString(),
  },
  {
    id: "folder-3",
    workspace_id: "workspace-1",
    name: "Product Photos",
    parent_folder_id: null,
    color: "#10b981",
    created_at: new Date("2024-02-01").toISOString(),
    updated_at: new Date("2024-02-01").toISOString(),
  },
  {
    id: "folder-4",
    workspace_id: "workspace-1",
    name: "Social Media Graphics",
    parent_folder_id: null,
    color: "#f59e0b",
    created_at: new Date("2024-03-01").toISOString(),
    updated_at: new Date("2024-03-01").toISOString(),
  },
  {
    id: "folder-5",
    workspace_id: "workspace-1",
    name: "Video Content",
    parent_folder_id: null,
    color: "#ef4444",
    created_at: new Date("2024-04-01").toISOString(),
    updated_at: new Date("2024-04-01").toISOString(),
  },
];

export const mockMediaTags: MediaTag[] = [
  {
    id: "tag-1",
    workspace_id: "workspace-1",
    name: "Campaign 2024",
    color: "#6366f1",
    created_at: new Date("2024-01-01").toISOString(),
  },
  {
    id: "tag-2",
    workspace_id: "workspace-1",
    name: "Product Launch",
    color: "#10b981",
    created_at: new Date("2024-01-05").toISOString(),
  },
  {
    id: "tag-3",
    workspace_id: "workspace-1",
    name: "Holiday",
    color: "#f59e0b",
    created_at: new Date("2024-01-10").toISOString(),
  },
  {
    id: "tag-4",
    workspace_id: "workspace-1",
    name: "User Generated",
    color: "#8b5cf6",
    created_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "tag-5",
    workspace_id: "workspace-1",
    name: "Stock",
    color: "#64748b",
    created_at: new Date("2024-01-20").toISOString(),
  },
];

export const mockMediaLibraryItems: MediaLibraryItem[] = [
  {
    id: "media-1",
    workspace_id: "workspace-1",
    folder_id: "folder-2",
    type: "image",
    url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=300",
    filename: "company-logo-primary.png",
    mime_type: "image/png",
    size_bytes: 245600,
    width: 1200,
    height: 800,
    duration: null,
    alt_text: "Company primary logo with blue gradient",
    description: "Main company logo for all marketing materials",
    tags: ["tag-1"],
    usage_count: 24,
    last_used_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "media-2",
    workspace_id: "workspace-1",
    folder_id: "folder-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300",
    filename: "product-headphones-hero.jpg",
    mime_type: "image/jpeg",
    size_bytes: 432100,
    width: 1920,
    height: 1080,
    duration: null,
    alt_text: "Black wireless headphones on orange background",
    description: "Hero shot for headphones product line",
    tags: ["tag-2"],
    usage_count: 12,
    last_used_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date("2024-02-10").toISOString(),
    updated_at: new Date("2024-02-10").toISOString(),
  },
  {
    id: "media-3",
    workspace_id: "workspace-1",
    folder_id: "folder-4",
    type: "image",
    url: "https://images.unsplash.com/photo-1557821552-17105176677c?w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1557821552-17105176677c?w=300",
    filename: "social-post-template-01.jpg",
    mime_type: "image/jpeg",
    size_bytes: 312400,
    width: 1080,
    height: 1080,
    duration: null,
    alt_text: "Instagram post template with colorful geometric shapes",
    description: "Template for Instagram carousel posts",
    tags: ["tag-1", "tag-3"],
    usage_count: 8,
    last_used_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date("2024-03-05").toISOString(),
    updated_at: new Date("2024-03-05").toISOString(),
  },
  {
    id: "media-4",
    workspace_id: "workspace-1",
    folder_id: "folder-5",
    type: "video",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=300",
    filename: "product-demo-video.mp4",
    mime_type: "video/mp4",
    size_bytes: 5242880,
    width: 1920,
    height: 1080,
    duration: 30,
    alt_text: null,
    description: "30-second product demonstration video",
    tags: ["tag-2"],
    usage_count: 6,
    last_used_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date("2024-04-01").toISOString(),
    updated_at: new Date("2024-04-01").toISOString(),
  },
  {
    id: "media-5",
    workspace_id: "workspace-1",
    folder_id: "folder-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=300",
    filename: "product-sunglasses.jpg",
    mime_type: "image/jpeg",
    size_bytes: 289700,
    width: 1500,
    height: 1000,
    duration: null,
    alt_text: "Stylish sunglasses on white background",
    description: "Product photo for summer collection",
    tags: ["tag-2", "tag-3"],
    usage_count: 15,
    last_used_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date("2024-05-10").toISOString(),
    updated_at: new Date("2024-05-10").toISOString(),
  },
  {
    id: "media-6",
    workspace_id: "workspace-1",
    folder_id: null,
    type: "gif",
    url: "https://media.giphy.com/media/26u4cqiYI30juCOGY/giphy.gif",
    thumbnail_url: "https://media.giphy.com/media/26u4cqiYI30juCOGY/giphy_s.gif",
    filename: "celebration-animation.gif",
    mime_type: "image/gif",
    size_bytes: 1524000,
    width: 480,
    height: 270,
    duration: 3,
    alt_text: "Animated celebration with confetti",
    description: "Celebration GIF for milestone posts",
    tags: ["tag-4"],
    usage_count: 3,
    last_used_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date("2024-06-01").toISOString(),
    updated_at: new Date("2024-06-01").toISOString(),
  },
  {
    id: "media-7",
    workspace_id: "workspace-1",
    folder_id: "folder-4",
    type: "image",
    url: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=300",
    filename: "team-collaboration.jpg",
    mime_type: "image/jpeg",
    size_bytes: 389500,
    width: 1600,
    height: 900,
    duration: null,
    alt_text: "Team members collaborating in modern office",
    description: "Stock photo for company culture posts",
    tags: ["tag-5"],
    usage_count: 7,
    last_used_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date("2024-07-15").toISOString(),
    updated_at: new Date("2024-07-15").toISOString(),
  },
  {
    id: "media-8",
    workspace_id: "workspace-1",
    folder_id: "folder-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
    thumbnail_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300",
    filename: "product-watch.jpg",
    mime_type: "image/jpeg",
    size_bytes: 298400,
    width: 1400,
    height: 1000,
    duration: null,
    alt_text: "Luxury watch on marble surface",
    description: "Product shot for premium watch line",
    tags: ["tag-2"],
    usage_count: 19,
    last_used_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date("2024-08-20").toISOString(),
    updated_at: new Date("2024-08-20").toISOString(),
  },
];

export function getMediaItemsByFolder(folderId: string | null): MediaLibraryItem[] {
  return mockMediaLibraryItems.filter((item) => item.folder_id === folderId);
}

export function getMediaItemsByTag(tagId: string): MediaLibraryItem[] {
  return mockMediaLibraryItems.filter((item) => item.tags.includes(tagId));
}

export function getMediaItemsByType(type: "image" | "video" | "gif"): MediaLibraryItem[] {
  return mockMediaLibraryItems.filter((item) => item.type === type);
}

export function searchMediaItems(query: string): MediaLibraryItem[] {
  const lowerQuery = query.toLowerCase();
  return mockMediaLibraryItems.filter(
    (item) =>
      item.filename.toLowerCase().includes(lowerQuery) ||
      item.description?.toLowerCase().includes(lowerQuery) ||
      item.alt_text?.toLowerCase().includes(lowerQuery)
  );
}
