import type { CustomFieldDefinition } from "../zod-schemas";

export const mockCustomFieldDefinitions: CustomFieldDefinition[] = [
  {
    id: "field-1",
    workspace_id: "workspace-1",
    field_name: "customer_id",
    field_label: "Customer ID",
    field_description: "Internal customer identifier",
    field_type: "text",
    is_required: false,
    is_unique: true,
    is_searchable: true,
    validation_rules: {
      pattern: "^CUST-[0-9]{6}$",
      min_length: 11,
      max_length: 11,
    },
    options: null,
    default_value: null,
    display_order: 1,
    placeholder: "CUST-000000",
    help_text: "Format: CUST-XXXXXX where X is a digit",
    field_group: "Business",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-2",
    workspace_id: "workspace-1",
    field_name: "lead_source",
    field_label: "Lead Source",
    field_description: "How this contact found you",
    field_type: "select",
    is_required: false,
    is_unique: false,
    is_searchable: true,
    validation_rules: {},
    options: [
      "Social Media",
      "Website",
      "Referral",
      "Event",
      "Advertisement",
      "Direct",
      "Other",
    ],
    default_value: "Website",
    display_order: 2,
    placeholder: "Select a lead source",
    help_text: null,
    field_group: "Marketing",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-3",
    workspace_id: "workspace-1",
    field_name: "annual_revenue",
    field_label: "Annual Revenue",
    field_description: "Estimated annual revenue",
    field_type: "currency",
    is_required: false,
    is_unique: false,
    is_searchable: false,
    validation_rules: {
      min_value: 0,
    },
    options: null,
    default_value: null,
    display_order: 3,
    placeholder: "0.00",
    help_text: "Enter in USD",
    field_group: "Business",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-4",
    workspace_id: "workspace-1",
    field_name: "employee_count",
    field_label: "Number of Employees",
    field_description: "Company size",
    field_type: "select",
    is_required: false,
    is_unique: false,
    is_searchable: true,
    validation_rules: {},
    options: ["1-10", "11-50", "51-200", "201-500", "501-1000", "1000+"],
    default_value: null,
    display_order: 4,
    placeholder: "Select company size",
    help_text: null,
    field_group: "Business",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-5",
    workspace_id: "workspace-1",
    field_name: "last_purchase_date",
    field_label: "Last Purchase Date",
    field_description: "Date of most recent purchase",
    field_type: "date",
    is_required: false,
    is_unique: false,
    is_searchable: false,
    validation_rules: {},
    options: null,
    default_value: null,
    display_order: 5,
    placeholder: "YYYY-MM-DD",
    help_text: null,
    field_group: "Sales",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-6",
    workspace_id: "workspace-1",
    field_name: "lifetime_value",
    field_label: "Lifetime Value",
    field_description: "Total customer lifetime value",
    field_type: "currency",
    is_required: false,
    is_unique: false,
    is_searchable: false,
    validation_rules: {
      min_value: 0,
    },
    options: null,
    default_value: "0",
    display_order: 6,
    placeholder: "0.00",
    help_text: "Total revenue from this customer",
    field_group: "Sales",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-7",
    workspace_id: "workspace-1",
    field_name: "industry",
    field_label: "Industry",
    field_description: "Business industry or sector",
    field_type: "select",
    is_required: false,
    is_unique: false,
    is_searchable: true,
    validation_rules: {},
    options: [
      "Technology",
      "Healthcare",
      "Finance",
      "Retail",
      "Manufacturing",
      "Education",
      "Real Estate",
      "Entertainment",
      "Other",
    ],
    default_value: null,
    display_order: 7,
    placeholder: "Select an industry",
    help_text: null,
    field_group: "Business",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-8",
    workspace_id: "workspace-1",
    field_name: "interests",
    field_label: "Interests",
    field_description: "Contact interests and preferences",
    field_type: "multiselect",
    is_required: false,
    is_unique: false,
    is_searchable: true,
    validation_rules: {},
    options: ["Products", "Services", "Partnership", "Press", "Support", "Careers"],
    default_value: null,
    display_order: 8,
    placeholder: "Select all that apply",
    help_text: "Can select multiple options",
    field_group: "Marketing",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-9",
    workspace_id: "workspace-1",
    field_name: "newsletter_subscribed",
    field_label: "Newsletter Subscription",
    field_description: "Subscribed to newsletter",
    field_type: "checkbox",
    is_required: false,
    is_unique: false,
    is_searchable: false,
    validation_rules: {},
    options: null,
    default_value: "false",
    display_order: 9,
    placeholder: null,
    help_text: "Check if subscribed to newsletter",
    field_group: "Marketing",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-01-15").toISOString(),
    updated_at: new Date("2024-01-15").toISOString(),
  },
  {
    id: "field-10",
    workspace_id: "workspace-1",
    field_name: "preferred_contact_method",
    field_label: "Preferred Contact Method",
    field_description: "How the contact prefers to be reached",
    field_type: "select",
    is_required: false,
    is_unique: false,
    is_searchable: true,
    validation_rules: {},
    options: ["Email", "Phone", "Social Media", "WhatsApp", "No Preference"],
    default_value: "Email",
    display_order: 10,
    placeholder: "Select preferred method",
    help_text: null,
    field_group: "Preferences",
    is_system: false,
    created_by: "user-1",
    created_at: new Date("2024-02-01").toISOString(),
    updated_at: new Date("2024-02-01").toISOString(),
  },
];

// Helper function to get custom fields by workspace
export function getCustomFieldsByWorkspace(workspaceId: string): CustomFieldDefinition[] {
  return mockCustomFieldDefinitions
    .filter((f) => f.workspace_id === workspaceId)
    .sort((a, b) => a.display_order - b.display_order);
}

// Helper function to get custom field by name
export function getCustomFieldByName(
  workspaceId: string,
  fieldName: string
): CustomFieldDefinition | undefined {
  return mockCustomFieldDefinitions.find(
    (f) => f.workspace_id === workspaceId && f.field_name === fieldName
  );
}

// Helper function to get custom fields by group
export function getCustomFieldsByGroup(
  workspaceId: string,
  group: string
): CustomFieldDefinition[] {
  return mockCustomFieldDefinitions
    .filter((f) => f.workspace_id === workspaceId && f.field_group === group)
    .sort((a, b) => a.display_order - b.display_order);
}

// Helper function to get all field groups for a workspace
export function getFieldGroups(workspaceId: string): string[] {
  const groups = mockCustomFieldDefinitions
    .filter((f) => f.workspace_id === workspaceId && f.field_group)
    .map((f) => f.field_group as string);

  return [...new Set(groups)].sort();
}
