import type {
  Integration,
  IntegrationCategory,
  IntegrationProvider,
  ProviderDefinition,
} from "../zod-schemas";

// Provider Definitions (28 total) - All available integrations
export const providerDefinitions: ProviderDefinition[] = [
  // Social Media (13)
  {
    id: "provider-x",
    provider: "x",
    name: "X (Twitter)",
    description:
      "Connect your X account to post tweets, manage DMs, and track engagement across your Twitter presence.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=x",
    features: [
      "Post tweets and threads",
      "Manage direct messages",
      "Track mentions and engagement",
      "Schedule posts",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url: "https://developer.twitter.com/en/docs",
  },
  {
    id: "provider-facebook",
    provider: "facebook",
    name: "Facebook",
    description:
      "Manage your Facebook pages, post updates, respond to comments, and analyze page performance.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=facebook",
    features: [
      "Post to pages",
      "Manage comments",
      "Access page insights",
      "Schedule content",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url: "https://developers.facebook.com/docs",
  },
  {
    id: "provider-instagram",
    provider: "instagram",
    name: "Instagram",
    description:
      "Post photos and videos, manage Instagram Stories, respond to comments and DMs on your business account.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=instagram",
    features: [
      "Post photos and videos",
      "Manage stories",
      "Respond to comments",
      "View insights",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url:
      "https://developers.facebook.com/docs/instagram-api",
  },
  {
    id: "provider-linkedin",
    provider: "linkedin",
    name: "LinkedIn",
    description:
      "Share professional updates, manage company pages, and engage with your LinkedIn network.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=linkedin",
    features: [
      "Post updates",
      "Manage company pages",
      "Share articles",
      "Track engagement",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url: "https://docs.microsoft.com/en-us/linkedin",
  },
  {
    id: "provider-reddit",
    provider: "reddit",
    name: "Reddit",
    description:
      "Post to subreddits, manage communities, respond to comments, and track post performance.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=reddit",
    features: [
      "Post to subreddits",
      "Manage posts",
      "Respond to comments",
      "Track karma",
    ],
    capabilities: ["read", "write", "moderation"],
    is_available: true,
    documentation_url: "https://www.reddit.com/dev/api",
  },
  {
    id: "provider-bluesky",
    provider: "bluesky",
    name: "Bluesky",
    description:
      "Connect to the decentralized Bluesky network, post updates, and engage with your followers.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=bluesky",
    features: ["Post updates", "Manage feeds", "Follow users", "Custom feeds"],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://docs.bsky.app",
  },
  {
    id: "provider-mastodon",
    provider: "mastodon",
    name: "Mastodon",
    description:
      "Connect to Mastodon instances, post toots, manage followers, and engage with the fediverse.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=mastodon",
    features: [
      "Post toots",
      "Manage visibility",
      "Content warnings",
      "Instance integration",
    ],
    capabilities: ["read", "write", "follow"],
    is_available: true,
    documentation_url: "https://docs.joinmastodon.org/api",
  },
  {
    id: "provider-threads",
    provider: "threads",
    name: "Threads",
    description:
      "Post to Meta's Threads platform, engage with conversations, and grow your audience.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=threads",
    features: [
      "Post threads",
      "Reply to conversations",
      "Manage followers",
      "Cross-post from Instagram",
    ],
    capabilities: ["read", "write"],
    is_available: true,
  },
  {
    id: "provider-tiktok",
    provider: "tiktok",
    name: "TikTok",
    description:
      "Upload videos, manage your TikTok business account, track analytics, and engage with comments.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=tiktok",
    features: [
      "Upload videos",
      "Manage comments",
      "View analytics",
      "Schedule posts",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url: "https://developers.tiktok.com",
  },
  {
    id: "provider-youtube",
    provider: "youtube",
    name: "YouTube",
    description:
      "Upload videos, manage your channel, respond to comments, and track video performance.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=youtube",
    features: [
      "Upload videos",
      "Manage playlists",
      "Respond to comments",
      "View analytics",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url: "https://developers.google.com/youtube",
  },
  {
    id: "provider-pinterest",
    provider: "pinterest",
    name: "Pinterest",
    description:
      "Create pins, manage boards, track engagement, and grow your Pinterest presence.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=pinterest",
    features: [
      "Create pins",
      "Manage boards",
      "Track analytics",
      "Schedule pins",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url: "https://developers.pinterest.com",
  },
  {
    id: "provider-farcaster",
    provider: "farcaster",
    name: "Farcaster",
    description:
      "Connect to the Farcaster protocol, cast messages, and engage with the decentralized social network.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=farcaster",
    features: [
      "Post casts",
      "Join channels",
      "React to content",
      "Follow users",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://docs.farcaster.xyz",
  },
  {
    id: "provider-nostr",
    provider: "nostr",
    name: "Nostr",
    description:
      "Connect to the Nostr protocol using relays, publish notes, and engage with the decentralized network.",
    category: "social-media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=nostr",
    features: [
      "Publish notes",
      "Manage relays",
      "Encrypted DMs",
      "Decentralized identity",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://nostr.com",
  },

  // Communication (4)
  {
    id: "provider-slack",
    provider: "slack",
    name: "Slack",
    description:
      "Send messages to channels, manage workspace, create bot integrations, and automate workflows.",
    category: "communication",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=slack",
    features: [
      "Send messages",
      "Manage channels",
      "Bot integration",
      "Webhook support",
    ],
    capabilities: ["read", "write", "bot"],
    is_available: true,
    documentation_url: "https://api.slack.com",
  },
  {
    id: "provider-discord",
    provider: "discord",
    name: "Discord",
    description:
      "Manage Discord servers, send messages to channels, create bots, and engage with communities.",
    category: "communication",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=discord",
    features: [
      "Send messages",
      "Manage servers",
      "Bot commands",
      "Embed messages",
    ],
    capabilities: ["read", "write", "bot"],
    is_available: true,
    documentation_url: "https://discord.com/developers/docs",
  },
  {
    id: "provider-telegram",
    provider: "telegram",
    name: "Telegram",
    description:
      "Create Telegram bots, send messages to groups and channels, and automate conversations.",
    category: "communication",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=telegram",
    features: [
      "Bot integration",
      "Group messaging",
      "Channel broadcasting",
      "Inline keyboards",
    ],
    capabilities: ["read", "write", "bot"],
    is_available: true,
    documentation_url: "https://core.telegram.org/bots/api",
  },
  {
    id: "provider-whatsapp",
    provider: "whatsapp",
    name: "WhatsApp Business",
    description:
      "Send messages via WhatsApp Business API, manage templates, and engage with customers.",
    category: "communication",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=whatsapp",
    features: [
      "Send messages",
      "Message templates",
      "Media sharing",
      "Business profile",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url:
      "https://developers.facebook.com/docs/whatsapp",
  },

  // Productivity (5)
  {
    id: "provider-notion",
    provider: "notion",
    name: "Notion",
    description:
      "Create pages, update databases, sync content, and integrate Notion with your workflows.",
    category: "productivity",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=notion",
    features: [
      "Create pages",
      "Update databases",
      "Search content",
      "Sync data",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://developers.notion.com",
  },
  {
    id: "provider-asana",
    provider: "asana",
    name: "Asana",
    description:
      "Create and manage tasks, update projects, track progress, and automate project workflows.",
    category: "productivity",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=asana",
    features: [
      "Create tasks",
      "Manage projects",
      "Track progress",
      "Automate workflows",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://developers.asana.com",
  },
  {
    id: "provider-clickup",
    provider: "clickup",
    name: "ClickUp",
    description:
      "Manage tasks, spaces, and lists, track time, and integrate ClickUp with your tools.",
    category: "productivity",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=clickup",
    features: [
      "Task management",
      "Time tracking",
      "Custom fields",
      "Workspace integration",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://clickup.com/api",
  },
  {
    id: "provider-monday",
    provider: "monday",
    name: "Monday.com",
    description:
      "Create items, update boards, manage workspaces, and automate Monday.com workflows.",
    category: "productivity",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=monday",
    features: [
      "Create items",
      "Update boards",
      "Custom columns",
      "Workflow automation",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://monday.com/developers",
  },
  {
    id: "provider-airtable",
    provider: "airtable",
    name: "Airtable",
    description:
      "Access bases, create records, update tables, and integrate Airtable databases with your apps.",
    category: "productivity",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=airtable",
    features: [
      "Access bases",
      "Create records",
      "Update tables",
      "Custom views",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://airtable.com/developers",
  },

  // Business (3)
  {
    id: "provider-salesforce",
    provider: "salesforce",
    name: "Salesforce",
    description:
      "Sync contacts, leads, and opportunities, manage CRM data, and automate sales workflows.",
    category: "business",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=salesforce",
    features: [
      "CRM sync",
      "Lead management",
      "Opportunity tracking",
      "Custom objects",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url: "https://developer.salesforce.com",
  },
  {
    id: "provider-google-my-business",
    provider: "google-my-business",
    name: "Google My Business",
    description:
      "Manage business profiles, post updates, respond to reviews, and track local SEO performance.",
    category: "business",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=gmb",
    features: [
      "Manage profiles",
      "Post updates",
      "Review management",
      "Location insights",
    ],
    capabilities: ["read", "write", "analytics"],
    is_available: true,
    documentation_url:
      "https://developers.google.com/my-business",
  },
  {
    id: "provider-trustpilot",
    provider: "trustpilot",
    name: "Trustpilot",
    description:
      "Monitor reviews, respond to customers, invite feedback, and track your business reputation.",
    category: "business",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=trustpilot",
    features: [
      "Review monitoring",
      "Customer responses",
      "Feedback invitations",
      "Reputation tracking",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://developers.trustpilot.com",
  },

  // Media (3)
  {
    id: "provider-cloudinary",
    provider: "cloudinary",
    name: "Cloudinary",
    description:
      "Upload and manage media, transform images and videos, optimize delivery, and use CDN features.",
    category: "media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=cloudinary",
    features: [
      "Media upload",
      "Image transformation",
      "Video processing",
      "CDN delivery",
    ],
    capabilities: ["read", "write", "transform"],
    is_available: true,
    documentation_url: "https://cloudinary.com/documentation",
  },
  {
    id: "provider-dropbox",
    provider: "dropbox",
    name: "Dropbox",
    description:
      "Upload files, manage folders, share content, and sync Dropbox with your applications.",
    category: "media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=dropbox",
    features: [
      "File upload",
      "Folder management",
      "File sharing",
      "Team folders",
    ],
    capabilities: ["read", "write", "share"],
    is_available: true,
    documentation_url: "https://www.dropbox.com/developers",
  },
  {
    id: "provider-dribbble",
    provider: "dribbble",
    name: "Dribbble",
    description:
      "Upload design shots, manage projects, showcase work, and engage with the design community.",
    category: "media",
    icon: "https://api.dicebear.com/7.x/shapes/svg?seed=dribbble",
    features: [
      "Upload shots",
      "Manage projects",
      "Design showcase",
      "Community engagement",
    ],
    capabilities: ["read", "write"],
    is_available: true,
    documentation_url: "https://developer.dribbble.com",
  },
];

// Connected Integration Instances (40+ instances)
export const mockIntegrations: Integration[] = [
  // Social Media - X/Twitter (3 instances)
  {
    id: "int-x-1",
    workspace_id: "workspace-1",
    provider: "x",
    provider_name: "X (Twitter)",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=x",
    category: "social-media",
    account_name: "@chatsian",
    account_identifier: "1234567890",
    status: "connected",
    connected_at: "2024-11-01T10:00:00Z",
    last_sync_at: "2024-11-22T08:30:00Z",
    token_expires_at: "2025-02-01T10:00:00Z",
    permissions: ["read_tweets", "write_tweets", "manage_dms"],
    settings: {
      default_visibility: "public",
      auto_retweet_mentions: false,
      enable_webhooks: true,
    },
    stats: {
      api_calls_today: 1247,
      api_calls_limit: 5000,
      items_synced: 342,
    },
    created_at: "2024-11-01T10:00:00Z",
    updated_at: "2024-11-22T08:30:00Z",
  },
  {
    id: "int-x-2",
    workspace_id: "workspace-1",
    provider: "x",
    provider_name: "X (Twitter)",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=x",
    category: "social-media",
    account_name: "@chatsian_support",
    account_identifier: "9876543210",
    status: "connected",
    connected_at: "2024-10-15T14:30:00Z",
    last_sync_at: "2024-11-22T07:15:00Z",
    token_expires_at: "2025-01-15T14:30:00Z",
    permissions: ["read_tweets", "write_tweets", "manage_dms"],
    settings: {
      default_visibility: "public",
      auto_retweet_mentions: true,
      enable_webhooks: false,
    },
    stats: {
      api_calls_today: 856,
      api_calls_limit: 5000,
      items_synced: 189,
    },
    created_at: "2024-10-15T14:30:00Z",
    updated_at: "2024-11-22T07:15:00Z",
  },
  {
    id: "int-x-3",
    workspace_id: "workspace-1",
    provider: "x",
    provider_name: "X (Twitter)",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=x",
    category: "social-media",
    account_name: "@chatsian_news",
    account_identifier: "5555555555",
    status: "error",
    connected_at: "2024-09-20T09:00:00Z",
    last_sync_at: "2024-11-20T12:00:00Z",
    token_expires_at: "2024-11-19T09:00:00Z",
    permissions: ["read_tweets", "write_tweets"],
    settings: {
      default_visibility: "public",
      auto_retweet_mentions: false,
      enable_webhooks: false,
    },
    error_message: "Access token expired. Please refresh your connection.",
    created_at: "2024-09-20T09:00:00Z",
    updated_at: "2024-11-20T12:00:00Z",
  },

  // Social Media - Facebook (2 instances)
  {
    id: "int-facebook-1",
    workspace_id: "workspace-1",
    provider: "facebook",
    provider_name: "Facebook",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=facebook",
    category: "social-media",
    account_name: "Chatsian Official",
    account_identifier: "page-123456",
    status: "connected",
    connected_at: "2024-10-10T11:00:00Z",
    last_sync_at: "2024-11-22T09:00:00Z",
    token_expires_at: "2025-01-10T11:00:00Z",
    permissions: ["pages_manage_posts", "pages_read_engagement"],
    settings: {
      default_post_type: "status",
      default_audience: "public",
    },
    stats: {
      api_calls_today: 432,
      api_calls_limit: 2000,
      items_synced: 78,
    },
    created_at: "2024-10-10T11:00:00Z",
    updated_at: "2024-11-22T09:00:00Z",
  },
  {
    id: "int-facebook-2",
    workspace_id: "workspace-1",
    provider: "facebook",
    provider_name: "Facebook",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=facebook",
    category: "social-media",
    account_name: "Chatsian Community",
    account_identifier: "page-789012",
    status: "connected",
    connected_at: "2024-11-05T15:30:00Z",
    last_sync_at: "2024-11-22T08:45:00Z",
    permissions: ["pages_manage_posts", "pages_read_engagement"],
    settings: {
      default_post_type: "photo",
      default_audience: "public",
    },
    stats: {
      api_calls_today: 234,
      api_calls_limit: 2000,
      items_synced: 45,
    },
    created_at: "2024-11-05T15:30:00Z",
    updated_at: "2024-11-22T08:45:00Z",
  },

  // Social Media - Instagram (2 instances)
  {
    id: "int-instagram-1",
    workspace_id: "workspace-1",
    provider: "instagram",
    provider_name: "Instagram",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=instagram",
    category: "social-media",
    account_name: "@chatsian",
    account_identifier: "ig-account-123",
    status: "connected",
    connected_at: "2024-10-05T10:00:00Z",
    last_sync_at: "2024-11-22T08:00:00Z",
    permissions: [
      "instagram_basic",
      "instagram_content_publish",
      "pages_read_engagement",
    ],
    settings: {
      default_aspect_ratio: "1:1",
      auto_hashtags: true,
      enable_stories: true,
    },
    stats: {
      api_calls_today: 567,
      api_calls_limit: 2000,
      items_synced: 123,
    },
    created_at: "2024-10-05T10:00:00Z",
    updated_at: "2024-11-22T08:00:00Z",
  },
  {
    id: "int-instagram-2",
    workspace_id: "workspace-1",
    provider: "instagram",
    provider_name: "Instagram",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=instagram",
    category: "social-media",
    account_name: "@chatsian_tips",
    account_identifier: "ig-account-456",
    status: "connected",
    connected_at: "2024-11-10T12:00:00Z",
    last_sync_at: "2024-11-22T07:30:00Z",
    permissions: ["instagram_basic", "instagram_content_publish"],
    settings: {
      default_aspect_ratio: "9:16",
      auto_hashtags: false,
      enable_stories: true,
    },
    stats: {
      api_calls_today: 289,
      api_calls_limit: 2000,
      items_synced: 67,
    },
    created_at: "2024-11-10T12:00:00Z",
    updated_at: "2024-11-22T07:30:00Z",
  },

  // Social Media - LinkedIn (2 instances)
  {
    id: "int-linkedin-1",
    workspace_id: "workspace-1",
    provider: "linkedin",
    provider_name: "LinkedIn",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=linkedin",
    category: "social-media",
    account_name: "Chatsian Inc.",
    account_identifier: "company-12345",
    status: "connected",
    connected_at: "2024-09-15T09:00:00Z",
    last_sync_at: "2024-11-22T08:15:00Z",
    permissions: ["w_member_social", "r_liteprofile", "r_organization_social"],
    settings: {
      default_visibility: "public",
      optimal_posting_time: true,
      timezone: "America/New_York",
    },
    stats: {
      api_calls_today: 145,
      api_calls_limit: 1000,
      items_synced: 34,
    },
    created_at: "2024-09-15T09:00:00Z",
    updated_at: "2024-11-22T08:15:00Z",
  },
  {
    id: "int-linkedin-2",
    workspace_id: "workspace-1",
    provider: "linkedin",
    provider_name: "LinkedIn",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=linkedin",
    category: "social-media",
    account_name: "John Doe (Personal)",
    account_identifier: "profile-67890",
    status: "connected",
    connected_at: "2024-10-20T14:00:00Z",
    last_sync_at: "2024-11-22T07:45:00Z",
    permissions: ["w_member_social", "r_liteprofile"],
    settings: {
      default_visibility: "connections",
      optimal_posting_time: false,
      timezone: "America/Los_Angeles",
    },
    stats: {
      api_calls_today: 67,
      api_calls_limit: 1000,
      items_synced: 12,
    },
    created_at: "2024-10-20T14:00:00Z",
    updated_at: "2024-11-22T07:45:00Z",
  },

  // Social Media - Reddit (1 instance)
  {
    id: "int-reddit-1",
    workspace_id: "workspace-1",
    provider: "reddit",
    provider_name: "Reddit",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=reddit",
    category: "social-media",
    account_name: "u/chatsian_official",
    account_identifier: "user-reddit-123",
    status: "connected",
    connected_at: "2024-10-25T13:00:00Z",
    last_sync_at: "2024-11-22T08:20:00Z",
    permissions: ["read", "submit", "edit", "modposts"],
    settings: {
      authorized_subreddits: ["r/socialmedia", "r/marketing", "r/startups"],
      default_flair: "Discussion",
      auto_approve_posts: false,
    },
    stats: {
      api_calls_today: 234,
      api_calls_limit: 1000,
      items_synced: 56,
    },
    created_at: "2024-10-25T13:00:00Z",
    updated_at: "2024-11-22T08:20:00Z",
  },

  // Social Media - Bluesky (1 instance)
  {
    id: "int-bluesky-1",
    workspace_id: "workspace-1",
    provider: "bluesky",
    provider_name: "Bluesky",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=bluesky",
    category: "social-media",
    account_name: "@chatsian.bsky.social",
    account_identifier: "did:plc:abc123",
    status: "connected",
    connected_at: "2024-11-12T10:30:00Z",
    last_sync_at: "2024-11-22T08:10:00Z",
    permissions: ["atproto.repo.createRecord", "atproto.repo.listRecords"],
    settings: {
      default_feed: "timeline",
      enable_content_warnings: false,
    },
    stats: {
      api_calls_today: 123,
      api_calls_limit: 3000,
      items_synced: 45,
    },
    created_at: "2024-11-12T10:30:00Z",
    updated_at: "2024-11-22T08:10:00Z",
  },

  // Social Media - Mastodon (1 instance)
  {
    id: "int-mastodon-1",
    workspace_id: "workspace-1",
    provider: "mastodon",
    provider_name: "Mastodon",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=mastodon",
    category: "social-media",
    account_name: "@chatsian@mastodon.social",
    account_identifier: "mastodon-user-123",
    status: "connected",
    connected_at: "2024-11-08T11:00:00Z",
    last_sync_at: "2024-11-22T08:05:00Z",
    permissions: ["read", "write", "follow", "push"],
    settings: {
      instance_url: "https://mastodon.social",
      default_visibility: "public",
      enable_content_warnings: true,
      default_cw_text: "",
    },
    stats: {
      api_calls_today: 89,
      api_calls_limit: 2000,
      items_synced: 23,
    },
    created_at: "2024-11-08T11:00:00Z",
    updated_at: "2024-11-22T08:05:00Z",
  },

  // Social Media - YouTube (1 instance)
  {
    id: "int-youtube-1",
    workspace_id: "workspace-1",
    provider: "youtube",
    provider_name: "YouTube",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=youtube",
    category: "social-media",
    account_name: "Chatsian Official",
    account_identifier: "channel-UC123456",
    status: "connected",
    connected_at: "2024-09-10T10:00:00Z",
    last_sync_at: "2024-11-22T07:00:00Z",
    permissions: [
      "youtube.upload",
      "youtube.readonly",
      "youtube.force-ssl",
    ],
    settings: {
      default_privacy: "public",
      default_category: "Science & Technology",
      monetization_enabled: true,
    },
    stats: {
      api_calls_today: 456,
      api_calls_limit: 10000,
      items_synced: 15,
    },
    created_at: "2024-09-10T10:00:00Z",
    updated_at: "2024-11-22T07:00:00Z",
  },

  // Social Media - TikTok (1 instance)
  {
    id: "int-tiktok-1",
    workspace_id: "workspace-1",
    provider: "tiktok",
    provider_name: "TikTok",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=tiktok",
    category: "social-media",
    account_name: "@chatsian",
    account_identifier: "tiktok-user-123",
    status: "connected",
    connected_at: "2024-11-01T09:00:00Z",
    last_sync_at: "2024-11-22T08:25:00Z",
    permissions: ["video.upload", "user.info.basic", "video.list"],
    settings: {
      default_privacy: "public_to_everyone",
      allow_comments: true,
      allow_duet: true,
      allow_stitch: true,
    },
    stats: {
      api_calls_today: 234,
      api_calls_limit: 1000,
      items_synced: 28,
    },
    created_at: "2024-11-01T09:00:00Z",
    updated_at: "2024-11-22T08:25:00Z",
  },

  // Social Media - Pinterest (1 instance)
  {
    id: "int-pinterest-1",
    workspace_id: "workspace-1",
    provider: "pinterest",
    provider_name: "Pinterest",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=pinterest",
    category: "social-media",
    account_name: "Chatsian",
    account_identifier: "pinterest-user-123",
    status: "connected",
    connected_at: "2024-10-18T12:00:00Z",
    last_sync_at: "2024-11-22T07:50:00Z",
    permissions: ["boards:read", "pins:read", "pins:write"],
    settings: {
      default_board: "Social Media Tips",
      enable_rich_pins: true,
      auto_add_source: true,
    },
    stats: {
      api_calls_today: 178,
      api_calls_limit: 1000,
      items_synced: 67,
    },
    created_at: "2024-10-18T12:00:00Z",
    updated_at: "2024-11-22T07:50:00Z",
  },

  // Social Media - Farcaster (1 instance)
  {
    id: "int-farcaster-1",
    workspace_id: "workspace-1",
    provider: "farcaster",
    provider_name: "Farcaster",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=farcaster",
    category: "social-media",
    account_name: "chatsian",
    account_identifier: "fid-12345",
    status: "connected",
    connected_at: "2024-11-15T14:00:00Z",
    last_sync_at: "2024-11-22T08:35:00Z",
    permissions: ["cast", "react", "follow"],
    settings: {
      default_channels: ["technology", "web3"],
      custody_address: "0x1234...5678",
    },
    stats: {
      api_calls_today: 67,
      api_calls_limit: 2000,
      items_synced: 34,
    },
    created_at: "2024-11-15T14:00:00Z",
    updated_at: "2024-11-22T08:35:00Z",
  },

  // Social Media - Nostr (1 instance)
  {
    id: "int-nostr-1",
    workspace_id: "workspace-1",
    provider: "nostr",
    provider_name: "Nostr",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=nostr",
    category: "social-media",
    account_name: "npub1abc...xyz",
    account_identifier: "npub1abcdefg123456",
    status: "connected",
    connected_at: "2024-11-18T15:00:00Z",
    last_sync_at: "2024-11-22T08:40:00Z",
    permissions: ["publish", "encrypt"],
    settings: {
      relays: [
        "wss://relay.damus.io",
        "wss://relay.snort.social",
        "wss://nos.lol",
      ],
      nip05_verification: "chatsian@chatsian.com",
      private_key_storage: "browser",
    },
    stats: {
      api_calls_today: 45,
      items_synced: 12,
    },
    created_at: "2024-11-18T15:00:00Z",
    updated_at: "2024-11-22T08:40:00Z",
  },

  // Communication - Slack (3 instances)
  {
    id: "int-slack-1",
    workspace_id: "workspace-1",
    provider: "slack",
    provider_name: "Slack",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=slack",
    category: "communication",
    account_name: "Chatsian Team",
    account_identifier: "T1234567",
    status: "connected",
    connected_at: "2024-09-01T10:00:00Z",
    last_sync_at: "2024-11-22T09:00:00Z",
    permissions: [
      "chat:write",
      "channels:read",
      "channels:manage",
      "users:read",
    ],
    settings: {
      bot_name: "Chatsian Bot",
      default_channel: "#general",
      enable_notifications: true,
    },
    stats: {
      api_calls_today: 1234,
      api_calls_limit: 20000,
      items_synced: 456,
    },
    created_at: "2024-09-01T10:00:00Z",
    updated_at: "2024-11-22T09:00:00Z",
  },
  {
    id: "int-slack-2",
    workspace_id: "workspace-1",
    provider: "slack",
    provider_name: "Slack",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=slack",
    category: "communication",
    account_name: "Chatsian Support",
    account_identifier: "T9876543",
    status: "connected",
    connected_at: "2024-10-05T11:00:00Z",
    last_sync_at: "2024-11-22T08:55:00Z",
    permissions: ["chat:write", "channels:read"],
    settings: {
      bot_name: "Support Bot",
      default_channel: "#support",
      enable_notifications: true,
    },
    stats: {
      api_calls_today: 567,
      api_calls_limit: 20000,
      items_synced: 234,
    },
    created_at: "2024-10-05T11:00:00Z",
    updated_at: "2024-11-22T08:55:00Z",
  },
  {
    id: "int-slack-3",
    workspace_id: "workspace-1",
    provider: "slack",
    provider_name: "Slack",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=slack",
    category: "communication",
    account_name: "Chatsian Community",
    account_identifier: "T5555555",
    status: "pending",
    connected_at: "2024-11-22T09:00:00Z",
    permissions: [],
    settings: {},
    created_at: "2024-11-22T09:00:00Z",
    updated_at: "2024-11-22T09:00:00Z",
  },

  // Communication - Discord (2 instances)
  {
    id: "int-discord-1",
    workspace_id: "workspace-1",
    provider: "discord",
    provider_name: "Discord",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=discord",
    category: "communication",
    account_name: "Chatsian Community",
    account_identifier: "guild-123456789",
    status: "connected",
    connected_at: "2024-09-20T12:00:00Z",
    last_sync_at: "2024-11-22T08:50:00Z",
    permissions: [
      "bot",
      "messages.read",
      "messages.write",
      "guilds.members.read",
    ],
    settings: {
      bot_username: "Chatsian Bot",
      bot_presence: "online",
      default_channel: "general",
    },
    stats: {
      api_calls_today: 789,
      api_calls_limit: 10000,
      items_synced: 345,
    },
    created_at: "2024-09-20T12:00:00Z",
    updated_at: "2024-11-22T08:50:00Z",
  },
  {
    id: "int-discord-2",
    workspace_id: "workspace-1",
    provider: "discord",
    provider_name: "Discord",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=discord",
    category: "communication",
    account_name: "Chatsian VIP",
    account_identifier: "guild-987654321",
    status: "connected",
    connected_at: "2024-11-10T13:00:00Z",
    last_sync_at: "2024-11-22T08:45:00Z",
    permissions: ["bot", "messages.read", "messages.write"],
    settings: {
      bot_username: "VIP Bot",
      bot_presence: "online",
      default_channel: "announcements",
    },
    stats: {
      api_calls_today: 234,
      api_calls_limit: 10000,
      items_synced: 89,
    },
    created_at: "2024-11-10T13:00:00Z",
    updated_at: "2024-11-22T08:45:00Z",
  },

  // Communication - Telegram (2 instances)
  {
    id: "int-telegram-1",
    workspace_id: "workspace-1",
    provider: "telegram",
    provider_name: "Telegram",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=telegram",
    category: "communication",
    account_name: "Chatsian Bot",
    account_identifier: "bot-123456789",
    status: "connected",
    connected_at: "2024-10-12T10:00:00Z",
    last_sync_at: "2024-11-22T09:05:00Z",
    permissions: ["messages", "group_messages"],
    settings: {
      bot_username: "@chatsian_bot",
      privacy_mode: false,
      enable_inline: true,
    },
    stats: {
      api_calls_today: 456,
      api_calls_limit: 30000,
      items_synced: 178,
    },
    created_at: "2024-10-12T10:00:00Z",
    updated_at: "2024-11-22T09:05:00Z",
  },
  {
    id: "int-telegram-2",
    workspace_id: "workspace-1",
    provider: "telegram",
    provider_name: "Telegram",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=telegram",
    category: "communication",
    account_name: "Chatsian Alerts",
    account_identifier: "bot-987654321",
    status: "connected",
    connected_at: "2024-11-15T11:00:00Z",
    last_sync_at: "2024-11-22T09:00:00Z",
    permissions: ["messages", "channels"],
    settings: {
      bot_username: "@chatsian_alerts",
      privacy_mode: true,
      enable_inline: false,
    },
    stats: {
      api_calls_today: 123,
      api_calls_limit: 30000,
      items_synced: 45,
    },
    created_at: "2024-11-15T11:00:00Z",
    updated_at: "2024-11-22T09:00:00Z",
  },

  // Communication - WhatsApp (1 instance)
  {
    id: "int-whatsapp-1",
    workspace_id: "workspace-1",
    provider: "whatsapp",
    provider_name: "WhatsApp Business",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=whatsapp",
    category: "communication",
    account_name: "+1 (555) 123-4567",
    account_identifier: "whatsapp-business-123",
    status: "connected",
    connected_at: "2024-10-01T09:00:00Z",
    last_sync_at: "2024-11-22T08:30:00Z",
    permissions: ["messages", "business_management"],
    settings: {
      business_profile: "Chatsian Support",
      enable_templates: true,
    },
    stats: {
      api_calls_today: 345,
      api_calls_limit: 1000,
      items_synced: 123,
    },
    created_at: "2024-10-01T09:00:00Z",
    updated_at: "2024-11-22T08:30:00Z",
  },

  // Productivity - Notion (3 instances)
  {
    id: "int-notion-1",
    workspace_id: "workspace-1",
    provider: "notion",
    provider_name: "Notion",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=notion",
    category: "productivity",
    account_name: "Chatsian Workspace",
    account_identifier: "workspace-notion-123",
    status: "connected",
    connected_at: "2024-08-15T10:00:00Z",
    last_sync_at: "2024-11-22T09:10:00Z",
    permissions: ["read_content", "insert_content", "update_content"],
    settings: {
      default_workspace: "Chatsian",
      accessible_databases: 15,
    },
    stats: {
      api_calls_today: 234,
      api_calls_limit: 3000,
      items_synced: 89,
    },
    created_at: "2024-08-15T10:00:00Z",
    updated_at: "2024-11-22T09:10:00Z",
  },
  {
    id: "int-notion-2",
    workspace_id: "workspace-1",
    provider: "notion",
    provider_name: "Notion",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=notion",
    category: "productivity",
    account_name: "Personal Workspace",
    account_identifier: "workspace-notion-456",
    status: "connected",
    connected_at: "2024-10-20T11:00:00Z",
    last_sync_at: "2024-11-22T09:05:00Z",
    permissions: ["read_content", "insert_content"],
    settings: {
      default_workspace: "Personal",
      accessible_databases: 5,
    },
    stats: {
      api_calls_today: 67,
      api_calls_limit: 3000,
      items_synced: 23,
    },
    created_at: "2024-10-20T11:00:00Z",
    updated_at: "2024-11-22T09:05:00Z",
  },
  {
    id: "int-notion-3",
    workspace_id: "workspace-1",
    provider: "notion",
    provider_name: "Notion",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=notion",
    category: "productivity",
    account_name: "Marketing Team",
    account_identifier: "workspace-notion-789",
    status: "connected",
    connected_at: "2024-11-01T12:00:00Z",
    last_sync_at: "2024-11-22T09:00:00Z",
    permissions: ["read_content", "insert_content", "update_content"],
    settings: {
      default_workspace: "Marketing",
      accessible_databases: 8,
    },
    stats: {
      api_calls_today: 145,
      api_calls_limit: 3000,
      items_synced: 56,
    },
    created_at: "2024-11-01T12:00:00Z",
    updated_at: "2024-11-22T09:00:00Z",
  },

  // Productivity - Asana (2 instances)
  {
    id: "int-asana-1",
    workspace_id: "workspace-1",
    provider: "asana",
    provider_name: "Asana",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=asana",
    category: "productivity",
    account_name: "Chatsian Team",
    account_identifier: "workspace-asana-123",
    status: "connected",
    connected_at: "2024-09-10T10:00:00Z",
    last_sync_at: "2024-11-22T08:55:00Z",
    permissions: ["default", "write"],
    settings: {
      default_project: "Marketing Campaigns",
      accessible_projects: 12,
    },
    stats: {
      api_calls_today: 345,
      api_calls_limit: 1500,
      items_synced: 134,
    },
    created_at: "2024-09-10T10:00:00Z",
    updated_at: "2024-11-22T08:55:00Z",
  },
  {
    id: "int-asana-2",
    workspace_id: "workspace-1",
    provider: "asana",
    provider_name: "Asana",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=asana",
    category: "productivity",
    account_name: "Product Team",
    account_identifier: "workspace-asana-456",
    status: "connected",
    connected_at: "2024-10-25T11:00:00Z",
    last_sync_at: "2024-11-22T08:50:00Z",
    permissions: ["default"],
    settings: {
      default_project: "Product Roadmap",
      accessible_projects: 6,
    },
    stats: {
      api_calls_today: 178,
      api_calls_limit: 1500,
      items_synced: 67,
    },
    created_at: "2024-10-25T11:00:00Z",
    updated_at: "2024-11-22T08:50:00Z",
  },

  // Productivity - ClickUp (1 instance)
  {
    id: "int-clickup-1",
    workspace_id: "workspace-1",
    provider: "clickup",
    provider_name: "ClickUp",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=clickup",
    category: "productivity",
    account_name: "Chatsian Workspace",
    account_identifier: "team-clickup-123",
    status: "connected",
    connected_at: "2024-10-15T10:00:00Z",
    last_sync_at: "2024-11-22T09:15:00Z",
    permissions: ["read", "write", "admin"],
    settings: {
      default_space: "Marketing",
      accessible_spaces: 5,
      enable_time_tracking: true,
    },
    stats: {
      api_calls_today: 456,
      api_calls_limit: 10000,
      items_synced: 234,
    },
    created_at: "2024-10-15T10:00:00Z",
    updated_at: "2024-11-22T09:15:00Z",
  },

  // Productivity - Monday (1 instance)
  {
    id: "int-monday-1",
    workspace_id: "workspace-1",
    provider: "monday",
    provider_name: "Monday.com",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=monday",
    category: "productivity",
    account_name: "Chatsian",
    account_identifier: "account-monday-123",
    status: "connected",
    connected_at: "2024-09-25T10:00:00Z",
    last_sync_at: "2024-11-22T09:20:00Z",
    permissions: ["boards:read", "boards:write"],
    settings: {
      default_board: "Content Calendar",
      accessible_boards: 8,
    },
    stats: {
      api_calls_today: 289,
      api_calls_limit: 10000,
      items_synced: 156,
    },
    created_at: "2024-09-25T10:00:00Z",
    updated_at: "2024-11-22T09:20:00Z",
  },

  // Productivity - Airtable (1 instance)
  {
    id: "int-airtable-1",
    workspace_id: "workspace-1",
    provider: "airtable",
    provider_name: "Airtable",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=airtable",
    category: "productivity",
    account_name: "Chatsian Workspace",
    account_identifier: "workspace-airtable-123",
    status: "connected",
    connected_at: "2024-11-05T10:00:00Z",
    last_sync_at: "2024-11-22T09:25:00Z",
    permissions: ["data:read", "data:write", "schema:read"],
    settings: {
      default_base: "Marketing Hub",
      accessible_bases: 4,
    },
    stats: {
      api_calls_today: 167,
      api_calls_limit: 5000,
      items_synced: 78,
    },
    created_at: "2024-11-05T10:00:00Z",
    updated_at: "2024-11-22T09:25:00Z",
  },

  // Business - Salesforce (2 instances)
  {
    id: "int-salesforce-1",
    workspace_id: "workspace-1",
    provider: "salesforce",
    provider_name: "Salesforce",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=salesforce",
    category: "business",
    account_name: "Chatsian Production",
    account_identifier: "org-00D123456",
    status: "connected",
    connected_at: "2024-08-01T10:00:00Z",
    last_sync_at: "2024-11-22T09:30:00Z",
    permissions: ["api", "refresh_token", "full"],
    settings: {
      instance_url: "https://chatsian.my.salesforce.com",
      org_type: "production",
      sync_frequency: "hourly",
    },
    stats: {
      api_calls_today: 2345,
      api_calls_limit: 100000,
      items_synced: 1234,
    },
    created_at: "2024-08-01T10:00:00Z",
    updated_at: "2024-11-22T09:30:00Z",
  },
  {
    id: "int-salesforce-2",
    workspace_id: "workspace-1",
    provider: "salesforce",
    provider_name: "Salesforce",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=salesforce",
    category: "business",
    account_name: "Chatsian Sandbox",
    account_identifier: "org-00D789012",
    status: "connected",
    connected_at: "2024-10-10T11:00:00Z",
    last_sync_at: "2024-11-22T09:25:00Z",
    permissions: ["api", "refresh_token"],
    settings: {
      instance_url: "https://chatsian--sandbox.my.salesforce.com",
      org_type: "sandbox",
      sync_frequency: "daily",
    },
    stats: {
      api_calls_today: 456,
      api_calls_limit: 100000,
      items_synced: 234,
    },
    created_at: "2024-10-10T11:00:00Z",
    updated_at: "2024-11-22T09:25:00Z",
  },

  // Business - Google My Business (1 instance)
  {
    id: "int-gmb-1",
    workspace_id: "workspace-1",
    provider: "google-my-business",
    provider_name: "Google My Business",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=gmb",
    category: "business",
    account_name: "Chatsian HQ",
    account_identifier: "location-gmb-123",
    status: "connected",
    connected_at: "2024-09-05T10:00:00Z",
    last_sync_at: "2024-11-22T08:40:00Z",
    permissions: ["business.manage", "posts.manage", "reviews.manage"],
    settings: {
      location_count: 3,
      auto_publish_posts: false,
      review_notification: true,
    },
    stats: {
      api_calls_today: 123,
      api_calls_limit: 1500,
      items_synced: 45,
    },
    created_at: "2024-09-05T10:00:00Z",
    updated_at: "2024-11-22T08:40:00Z",
  },

  // Business - Trustpilot (1 instance)
  {
    id: "int-trustpilot-1",
    workspace_id: "workspace-1",
    provider: "trustpilot",
    provider_name: "Trustpilot",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=trustpilot",
    category: "business",
    account_name: "Chatsian",
    account_identifier: "business-trustpilot-123",
    status: "connected",
    connected_at: "2024-10-01T10:00:00Z",
    last_sync_at: "2024-11-22T08:35:00Z",
    permissions: ["reviews:read", "reviews:respond"],
    settings: {
      review_score: 4.8,
      total_reviews: 1247,
      auto_respond: false,
    },
    stats: {
      api_calls_today: 89,
      api_calls_limit: 1000,
      items_synced: 34,
    },
    created_at: "2024-10-01T10:00:00Z",
    updated_at: "2024-11-22T08:35:00Z",
  },

  // Media - Cloudinary (2 instances)
  {
    id: "int-cloudinary-1",
    workspace_id: "workspace-1",
    provider: "cloudinary",
    provider_name: "Cloudinary",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=cloudinary",
    category: "media",
    account_name: "chatsian-prod",
    account_identifier: "cloud-cloudinary-prod",
    status: "connected",
    connected_at: "2024-07-15T10:00:00Z",
    last_sync_at: "2024-11-22T09:35:00Z",
    permissions: ["upload", "transform", "admin"],
    settings: {
      cloud_name: "chatsian-prod",
      default_folder: "social-media",
      upload_preset: "ml_default",
      auto_optimize: true,
      default_quality: "auto",
    },
    stats: {
      storage_used: 45670,
      storage_limit: 100000,
      api_calls_today: 3456,
      api_calls_limit: 25000,
    },
    created_at: "2024-07-15T10:00:00Z",
    updated_at: "2024-11-22T09:35:00Z",
  },
  {
    id: "int-cloudinary-2",
    workspace_id: "workspace-1",
    provider: "cloudinary",
    provider_name: "Cloudinary",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=cloudinary",
    category: "media",
    account_name: "chatsian-dev",
    account_identifier: "cloud-cloudinary-dev",
    status: "connected",
    connected_at: "2024-09-20T11:00:00Z",
    last_sync_at: "2024-11-22T09:30:00Z",
    permissions: ["upload", "transform"],
    settings: {
      cloud_name: "chatsian-dev",
      default_folder: "test",
      upload_preset: "development",
      auto_optimize: false,
      default_quality: "high",
    },
    stats: {
      storage_used: 12340,
      storage_limit: 25000,
      api_calls_today: 567,
      api_calls_limit: 10000,
    },
    created_at: "2024-09-20T11:00:00Z",
    updated_at: "2024-11-22T09:30:00Z",
  },

  // Media - Dropbox (1 instance)
  {
    id: "int-dropbox-1",
    workspace_id: "workspace-1",
    provider: "dropbox",
    provider_name: "Dropbox",
    provider_icon: "https://api.dicebear.com/7.x/shapes/svg?seed=dropbox",
    category: "media",
    account_name: "team@chatsian.com",
    account_identifier: "team-dropbox-123",
    status: "connected",
    connected_at: "2024-08-20T10:00:00Z",
    last_sync_at: "2024-11-22T09:20:00Z",
    permissions: [
      "files.content.read",
      "files.content.write",
      "sharing.write",
    ],
    settings: {
      account_type: "business",
      default_folder: "/Chatsian/Media",
      auto_sync: true,
    },
    stats: {
      storage_used: 234567,
      storage_limit: 2000000,
      api_calls_today: 234,
      api_calls_limit: 10000,
    },
    created_at: "2024-08-20T10:00:00Z",
    updated_at: "2024-11-22T09:20:00Z",
  },
];

// Helper functions
export function getIntegrationById(id: string): Integration | undefined {
  return mockIntegrations.find((integration) => integration.id === id);
}

export function getIntegrationsByCategory(
  category: IntegrationCategory
): Integration[] {
  return mockIntegrations.filter(
    (integration) => integration.category === category
  );
}

export function getIntegrationsByProvider(
  provider: IntegrationProvider
): Integration[] {
  return mockIntegrations.filter(
    (integration) => integration.provider === provider
  );
}

export function getConnectedIntegrations(): Integration[] {
  return mockIntegrations.filter(
    (integration) => integration.status === "connected"
  );
}

export function getProviderDefinition(
  provider: IntegrationProvider
): ProviderDefinition | undefined {
  return providerDefinitions.find((def) => def.provider === provider);
}

export function getAvailableProviders(): ProviderDefinition[] {
  return providerDefinitions.filter((def) => def.is_available);
}

export function getProvidersByCategory(
  category: IntegrationCategory
): ProviderDefinition[] {
  return providerDefinitions.filter((def) => def.category === category);
}
