import type { ConversationNote } from "../zod-schemas";

const now = Date.now();

export const mockConversationNotes: ConversationNote[] = [
  // Notes for conversation 1 (Sarah Chen - Twitter)
  {
    id: "note-1-1",
    workspace_id: "workspace-1",
    conversation_id: "conv-1",
    content: "Sarah is a VIP client. She's mentioned interest in our enterprise features before. High priority for partnership discussions.",
    note_type: "internal",
    visibility: "team",
    author_id: "user-1",
    author_name: "You (Current User)",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=You",
    mentioned_user_ids: ["user-2"],
    is_pinned: true,
    created_at: new Date(now - 7000000).toISOString(),
    updated_at: new Date(now - 7000000).toISOString(),
  },
  {
    id: "note-1-2",
    workspace_id: "workspace-1",
    conversation_id: "conv-1",
    content: "Follow up on partnership call by end of week. She's very interested in the automation features.",
    note_type: "follow_up",
    visibility: "team",
    author_id: "user-2",
    author_name: "Sarah Johnson",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    mentioned_user_ids: [],
    is_pinned: false,
    created_at: new Date(now - 3600000).toISOString(),
    updated_at: new Date(now - 3600000).toISOString(),
  },

  // Notes for conversation 3 (John Doe - WhatsApp)
  {
    id: "note-3-1",
    workspace_id: "workspace-1",
    conversation_id: "conv-3",
    content: "Customer is interested in enterprise plan. Needs demo scheduled for next week. Check calendar availability.",
    note_type: "action_item",
    visibility: "team",
    author_id: "user-2",
    author_name: "Sarah Johnson",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    mentioned_user_ids: ["user-1"],
    is_pinned: false,
    created_at: new Date(now - 7000000).toISOString(),
    updated_at: new Date(now - 7000000).toISOString(),
  },
  {
    id: "note-3-2",
    workspace_id: "workspace-1",
    conversation_id: "conv-3",
    content: "Demo scheduled for Thursday 2PM EST. Sent calendar invite.",
    note_type: "general",
    visibility: "team",
    author_id: "user-2",
    author_name: "Sarah Johnson",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    mentioned_user_ids: [],
    is_pinned: false,
    created_at: new Date(now - 3600000).toISOString(),
    updated_at: new Date(now - 3600000).toISOString(),
  },

  // Notes for conversation 5 (Michael Brown - LinkedIn)
  {
    id: "note-5-1",
    workspace_id: "workspace-1",
    conversation_id: "conv-5",
    content: "VIP ALERT: Enterprise Solutions Corp is a Fortune 500 company. This could be a massive deal. Treat with highest priority.",
    note_type: "escalation",
    visibility: "team",
    author_id: "user-1",
    author_name: "You (Current User)",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=You",
    mentioned_user_ids: ["user-2", "user-3"],
    is_pinned: true,
    created_at: new Date(now - 400000000).toISOString(),
    updated_at: new Date(now - 400000000).toISOString(),
  },
  {
    id: "note-5-2",
    workspace_id: "workspace-1",
    conversation_id: "conv-5",
    content: "Michael is VP of Sales. Decision maker for their social media toolstack. Budget is not a concern.",
    note_type: "internal",
    visibility: "team",
    author_id: "user-1",
    author_name: "You (Current User)",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=You",
    mentioned_user_ids: [],
    is_pinned: false,
    created_at: new Date(now - 350000000).toISOString(),
    updated_at: new Date(now - 350000000).toISOString(),
  },

  // Notes for conversation 6 (Jessica - Discord)
  {
    id: "note-6-1",
    workspace_id: "workspace-1",
    conversation_id: "conv-6",
    content: "Customer reported a bug with the Discord integration. Engineering team notified. Ticket #1234 created.",
    note_type: "action_item",
    visibility: "team",
    author_id: "user-3",
    author_name: "Mike Peters",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    mentioned_user_ids: ["user-4"],
    is_pinned: false,
    created_at: new Date(now - 20000000).toISOString(),
    updated_at: new Date(now - 20000000).toISOString(),
  },

  // Notes for conversation 12 (David Kim - Instagram)
  {
    id: "note-12-1",
    workspace_id: "workspace-1",
    conversation_id: "conv-12",
    content: "David Kim is a major influencer with 500K+ followers. Interested in brand partnership for our Q1 campaign.",
    note_type: "internal",
    visibility: "team",
    author_id: "user-2",
    author_name: "Sarah Johnson",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    mentioned_user_ids: [],
    is_pinned: true,
    created_at: new Date(now - 1000000000).toISOString(),
    updated_at: new Date(now - 1000000000).toISOString(),
  },
  {
    id: "note-12-2",
    workspace_id: "workspace-1",
    conversation_id: "conv-12",
    content: "Negotiating partnership terms. He's asking for $15K per campaign post. Waiting on budget approval from marketing.",
    note_type: "action_item",
    visibility: "team",
    author_id: "user-2",
    author_name: "Sarah Johnson",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    mentioned_user_ids: ["user-1"],
    is_pinned: false,
    created_at: new Date(now - 500000000).toISOString(),
    updated_at: new Date(now - 500000000).toISOString(),
  },
  {
    id: "note-12-3",
    workspace_id: "workspace-1",
    conversation_id: "conv-12",
    content: "Contract sent via email. Awaiting signature. Expected to close by end of month.",
    note_type: "follow_up",
    visibility: "team",
    author_id: "user-2",
    author_name: "Sarah Johnson",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    mentioned_user_ids: [],
    is_pinned: false,
    created_at: new Date(now - 172800000).toISOString(),
    updated_at: new Date(now - 172800000).toISOString(),
  },

  // Notes for conversation 15 (David Kim - Twitter)
  {
    id: "note-15-1",
    workspace_id: "workspace-1",
    conversation_id: "conv-15",
    content: "PUBLIC MENTION! David Kim mentioned us in a tweet to his 89K followers. Great exposure opportunity!",
    note_type: "escalation",
    visibility: "team",
    author_id: "user-1",
    author_name: "You (Current User)",
    author_avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=You",
    mentioned_user_ids: ["user-2", "user-3", "user-4"],
    is_pinned: true,
    created_at: new Date(now - 900000).toISOString(),
    updated_at: new Date(now - 900000).toISOString(),
  },
];

// Export function to get notes by conversation
export function getNotesByConversation(conversationId: string): ConversationNote[] {
  return mockConversationNotes.filter(n => n.conversation_id === conversationId);
}
