import type { Person } from "../zod-schemas";

export const mockPeople: Person[] = [
  {
    id: "person-1",
    workspace_id: "workspace-1",
    email: "sarah.chen@example.com",
    full_name: "Sarah Chen",
    display_name: "Sarah Chen",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahChen",
    phone: "+1-555-0101",
    location: "San Francisco, CA",
    timezone: "America/Los_Angeles",
    language: "en",
    bio: "Tech entrepreneur and angel investor. Passionate about AI and sustainable technology.",
    company: "TechVentures Inc",
    job_title: "CEO",
    website_url: "https://sarahchen.com",
    first_contact_at: new Date("2024-11-01").toISOString(),
    last_contact_at: new Date().toISOString(),
    total_messages: 47,
    total_conversations: 3,
    is_vip: true,
    is_verified: true,
    is_blocked: false,
    tags: ["VIP", "Customer", "Verified"],
    custom_fields: {},
    metadata: {},
    created_at: new Date("2024-11-01").toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "person-2",
    workspace_id: "workspace-1",
    email: "john.doe@example.com",
    full_name: "John Doe",
    display_name: "John",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=JohnDoe",
    phone: "+1-555-0102",
    location: "New York, NY",
    timezone: "America/New_York",
    language: "en",
    bio: "Digital marketing professional",
    company: "Marketing Pro LLC",
    job_title: "Marketing Manager",
    website_url: null,
    first_contact_at: new Date("2024-11-15").toISOString(),
    last_contact_at: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
    total_messages: 12,
    total_conversations: 1,
    is_vip: false,
    is_verified: false,
    is_blocked: false,
    tags: ["Customer"],
    custom_fields: {},
    metadata: {},
    created_at: new Date("2024-11-15").toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "person-3",
    workspace_id: "workspace-1",
    email: "emily.rodriguez@example.com",
    full_name: "Emily Rodriguez",
    display_name: "Emily",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=EmilyRodriguez",
    phone: null,
    location: "Miami, FL",
    timezone: "America/New_York",
    language: "en",
    bio: "Content creator | Fashion & Lifestyle 👗✨",
    company: null,
    job_title: "Influencer",
    website_url: "https://emilyrodriguez.co",
    first_contact_at: new Date("2024-10-20").toISOString(),
    last_contact_at: new Date(Date.now() - 7200000).toISOString(), // 2 hours ago
    total_messages: 28,
    total_conversations: 2,
    is_vip: false,
    is_verified: true,
    is_blocked: false,
    tags: ["Influencer", "Verified"],
    custom_fields: {},
    metadata: {},
    created_at: new Date("2024-10-20").toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "person-4",
    workspace_id: "workspace-1",
    email: "michael.brown@example.com",
    full_name: "Michael Brown",
    display_name: "Michael Brown",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=MichaelBrown",
    phone: "+1-555-0104",
    location: "Chicago, IL",
    timezone: "America/Chicago",
    language: "en",
    bio: "B2B Sales Executive specializing in enterprise solutions",
    company: "Enterprise Solutions Corp",
    job_title: "VP of Sales",
    website_url: "https://linkedin.com/in/michaelbrown",
    first_contact_at: new Date("2024-09-10").toISOString(),
    last_contact_at: new Date("2024-12-15").toISOString(),
    total_messages: 8,
    total_conversations: 1,
    is_vip: true,
    is_verified: false,
    is_blocked: false,
    tags: ["VIP", "B2B", "Enterprise"],
    custom_fields: {},
    metadata: {},
    created_at: new Date("2024-09-10").toISOString(),
    updated_at: new Date("2024-12-15").toISOString(),
  },
  {
    id: "person-5",
    workspace_id: "workspace-1",
    email: "jessica.taylor@example.com",
    full_name: "Jessica Taylor",
    display_name: "Jess",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=JessicaTaylor",
    phone: null,
    location: "Austin, TX",
    timezone: "America/Chicago",
    language: "en",
    bio: "Customer support inquiry",
    company: null,
    job_title: null,
    website_url: null,
    first_contact_at: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
    last_contact_at: new Date(Date.now() - 86400000).toISOString(),
    total_messages: 5,
    total_conversations: 1,
    is_vip: false,
    is_verified: false,
    is_blocked: false,
    tags: ["Support"],
    custom_fields: {},
    metadata: {},
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "person-6",
    workspace_id: "workspace-1",
    email: "david.kim@example.com",
    full_name: "David Kim",
    display_name: "David Kim",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidKim",
    phone: null,
    location: "Los Angeles, CA",
    timezone: "America/Los_Angeles",
    language: "en",
    bio: "🎥 Content Creator | 500K+ Followers | Brand Partnerships",
    company: null,
    job_title: "Content Creator",
    website_url: "https://davidkim.tv",
    first_contact_at: new Date("2024-11-20").toISOString(),
    last_contact_at: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
    total_messages: 15,
    total_conversations: 2,
    is_vip: true,
    is_verified: true,
    is_blocked: false,
    tags: ["VIP", "Influencer", "Verified", "Partnership"],
    custom_fields: {},
    metadata: {},
    created_at: new Date("2024-11-20").toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "person-7",
    workspace_id: "workspace-1",
    email: "spam.user@example.com",
    full_name: "Spam User",
    display_name: "Spam",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=SpamUser",
    phone: null,
    location: null,
    timezone: null,
    language: "en",
    bio: null,
    company: null,
    job_title: null,
    website_url: null,
    first_contact_at: new Date(Date.now() - 604800000).toISOString(), // 1 week ago
    last_contact_at: new Date(Date.now() - 604800000).toISOString(),
    total_messages: 2,
    total_conversations: 1,
    is_vip: false,
    is_verified: false,
    is_blocked: true,
    tags: ["Spam", "Blocked"],
    custom_fields: {},
    metadata: {},
    created_at: new Date(Date.now() - 604800000).toISOString(),
    updated_at: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: "person-8",
    workspace_id: "workspace-1",
    email: "robert.martinez@example.com",
    full_name: "Robert Martinez",
    display_name: "Robert",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=RobertMartinez",
    phone: "+1-555-0108",
    location: "Seattle, WA",
    timezone: "America/Los_Angeles",
    language: "en",
    bio: "Software engineer interested in your product",
    company: "Tech Startup",
    job_title: "Senior Engineer",
    website_url: null,
    first_contact_at: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
    last_contact_at: new Date(Date.now() - 3600000).toISOString(),
    total_messages: 3,
    total_conversations: 1,
    is_vip: false,
    is_verified: false,
    is_blocked: false,
    tags: ["New", "Prospect"],
    custom_fields: {},
    metadata: {},
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
];
