import type { PostWithAuthor } from "../zod-schemas";

const now = Date.now();

export const mockPosts: PostWithAuthor[] = [
  // Published posts (last 2 weeks)
  {
    id: "post-1",
    workspace_id: "workspace-1",
    author_id: "user-1",
    content: "Excited to announce our new feature! 🚀 Now you can schedule posts across all your social media platforms from one place. #SocialMedia #ProductLaunch",
    media: [
      {
        id: "media-post-1",
        type: "image",
        url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
        thumbnail_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
        alt_text: "Product launch banner",
        width: 1200,
        height: 630,
        duration_seconds: null,
      },
    ],
    poll: null,
    link_preview: null,
    type: "image",
    platforms: ["twitter", "linkedin", "facebook"],
    platform_settings: [
      {
        platform: "twitter",
        account_id: "account-1",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "tw-12345",
        platform_url: "https://twitter.com/chatsian/status/12345",
        published_at: new Date(now - 86400000).toISOString(), // 1 day ago
        status: "published",
        error_message: null,
      },
      {
        platform: "linkedin",
        account_id: "account-4",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "li-67890",
        platform_url: "https://linkedin.com/posts/chatsian-67890",
        published_at: new Date(now - 86400000).toISOString(),
        status: "published",
        error_message: null,
      },
      {
        platform: "facebook",
        account_id: "account-5",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "fb-11223",
        platform_url: "https://facebook.com/chatsian/posts/11223",
        published_at: new Date(now - 86400000).toISOString(),
        status: "published",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now - 86400000).toISOString(),
    published_at: new Date(now - 86400000).toISOString(),
    status: "published",
    hashtags: ["SocialMedia", "ProductLaunch"],
    mentions: [],
    tags: ["product", "announcement"],
    approval_status: "approved",
    approved_by: "user-2",
    approved_at: new Date(now - 172800000).toISOString(),
    assigned_to: "user-1",
    engagement: {
      likes: 234,
      comments: 18,
      shares: 42,
      saves: 15,
      impressions: 5420,
      reach: 3890,
      clicks: 156,
      engagement_rate: 5.8,
    },
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 259200000).toISOString(),
    updated_at: new Date(now - 86400000).toISOString(),
    author: {
      id: "user-1",
      full_name: "Sarah Johnson",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    },
  },

  {
    id: "post-2",
    workspace_id: "workspace-1",
    author_id: "user-2",
    content: "Quick tip: The best time to post on Instagram is between 6-9 PM on weekdays! 📊 #SocialMediaTips #Marketing",
    media: [],
    poll: null,
    link_preview: null,
    type: "text",
    platforms: ["twitter", "instagram", "threads"],
    platform_settings: [
      {
        platform: "twitter",
        account_id: "account-1",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "tw-22334",
        platform_url: "https://twitter.com/chatsian/status/22334",
        published_at: new Date(now - 172800000).toISOString(), // 2 days ago
        status: "published",
        error_message: null,
      },
      {
        platform: "instagram",
        account_id: "account-3",
        content_override: null,
        first_comment: "What's your favorite time to post? Let us know! 👇",
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "ig-33445",
        platform_url: "https://instagram.com/p/33445",
        published_at: new Date(now - 172800000).toISOString(),
        status: "published",
        error_message: null,
      },
      {
        platform: "threads",
        account_id: "account-8",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "threads-44556",
        platform_url: "https://threads.net/@chatsian/post/44556",
        published_at: new Date(now - 172800000).toISOString(),
        status: "published",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now - 172800000).toISOString(),
    published_at: new Date(now - 172800000).toISOString(),
    status: "published",
    hashtags: ["SocialMediaTips", "Marketing"],
    mentions: [],
    tags: ["tips", "education"],
    approval_status: "approved",
    approved_by: "user-1",
    approved_at: new Date(now - 259200000).toISOString(),
    assigned_to: "user-2",
    engagement: {
      likes: 189,
      comments: 24,
      shares: 31,
      saves: 45,
      impressions: 4230,
      reach: 2890,
      clicks: 98,
      engagement_rate: 6.8,
    },
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 345600000).toISOString(),
    updated_at: new Date(now - 172800000).toISOString(),
    author: {
      id: "user-2",
      full_name: "Mike Chen",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    },
  },

  {
    id: "post-3",
    workspace_id: "workspace-1",
    author_id: "user-1",
    content: "Behind the scenes at our team retreat! 🌴 Building the future of social media management together. #TeamCulture #CompanyLife",
    media: [
      {
        id: "media-post-3",
        type: "image",
        url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c",
        thumbnail_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400",
        alt_text: "Team meeting",
        width: 1200,
        height: 800,
        duration_seconds: null,
      },
    ],
    poll: null,
    link_preview: null,
    type: "image",
    platforms: ["instagram", "linkedin"],
    platform_settings: [
      {
        platform: "instagram",
        account_id: "account-3",
        content_override: null,
        first_comment: "Swipe to see more photos from our retreat! ➡️",
        thread_tweets: null,
        location_tag: "Bali, Indonesia",
        tagged_users: ["@teammember1", "@teammember2"],
        platform_post_id: "ig-55667",
        platform_url: "https://instagram.com/p/55667",
        published_at: new Date(now - 345600000).toISOString(), // 4 days ago
        status: "published",
        error_message: null,
      },
      {
        platform: "linkedin",
        account_id: "account-4",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "li-78901",
        platform_url: "https://linkedin.com/posts/chatsian-78901",
        published_at: new Date(now - 345600000).toISOString(),
        status: "published",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now - 345600000).toISOString(),
    published_at: new Date(now - 345600000).toISOString(),
    status: "published",
    hashtags: ["TeamCulture", "CompanyLife"],
    mentions: [],
    tags: ["team", "culture"],
    approval_status: "approved",
    approved_by: "user-2",
    approved_at: new Date(now - 432000000).toISOString(),
    assigned_to: "user-1",
    engagement: {
      likes: 456,
      comments: 32,
      shares: 28,
      saves: 12,
      impressions: 8920,
      reach: 6540,
      clicks: 234,
      engagement_rate: 6.3,
    },
    is_pinned: true,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 518400000).toISOString(),
    updated_at: new Date(now - 345600000).toISOString(),
    author: {
      id: "user-1",
      full_name: "Sarah Johnson",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    },
  },

  // Scheduled posts (future)
  {
    id: "post-4",
    workspace_id: "workspace-1",
    author_id: "user-1",
    content: "New blog post alert! 📝 Learn how to create a content calendar that actually works. Link in bio! #ContentMarketing #BlogPost",
    media: [
      {
        id: "media-post-4",
        type: "image",
        url: "https://images.unsplash.com/photo-1499750310107-5fef28a66643",
        thumbnail_url: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400",
        alt_text: "Content calendar blog post",
        width: 1200,
        height: 630,
        duration_seconds: null,
      },
    ],
    poll: null,
    link_preview: {
      url: "https://chatsian.com/blog/content-calendar-guide",
      title: "The Ultimate Guide to Creating a Content Calendar",
      description: "Step-by-step guide to planning and scheduling your social media content effectively.",
      image_url: "https://images.unsplash.com/photo-1499750310107-5fef28a66643",
      shortened_url: "https://chatsian.co/cal-guide",
    },
    type: "link",
    platforms: ["twitter", "linkedin", "facebook"],
    platform_settings: [
      {
        platform: "twitter",
        account_id: "account-1",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "linkedin",
        account_id: "account-4",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "facebook",
        account_id: "account-5",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now + 86400000).toISOString(), // Tomorrow
    published_at: null,
    status: "scheduled",
    hashtags: ["ContentMarketing", "BlogPost"],
    mentions: [],
    tags: ["blog", "content"],
    approval_status: "approved",
    approved_by: "user-2",
    approved_at: new Date(now - 3600000).toISOString(),
    assigned_to: "user-1",
    engagement: null,
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 86400000).toISOString(),
    updated_at: new Date(now - 3600000).toISOString(),
    author: {
      id: "user-1",
      full_name: "Sarah Johnson",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    },
  },

  {
    id: "post-5",
    workspace_id: "workspace-1",
    author_id: "user-2",
    content: "Poll time! 🗳️ What's your biggest challenge with social media management?",
    media: [],
    poll: {
      question: "What's your biggest challenge with social media management?",
      options: [
        "Creating content consistently",
        "Scheduling and timing",
        "Analyzing performance",
        "Managing multiple platforms",
      ],
      duration_hours: 24,
    },
    link_preview: null,
    type: "poll",
    platforms: ["twitter", "instagram"],
    platform_settings: [
      {
        platform: "twitter",
        account_id: "account-1",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "instagram",
        account_id: "account-3",
        content_override: null,
        first_comment: "Vote in our story! 👆",
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now + 172800000).toISOString(), // 2 days from now
    published_at: null,
    status: "scheduled",
    hashtags: [],
    mentions: [],
    tags: ["engagement", "poll"],
    approval_status: "approved",
    approved_by: "user-1",
    approved_at: new Date(now - 7200000).toISOString(),
    assigned_to: "user-2",
    engagement: null,
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 43200000).toISOString(),
    updated_at: new Date(now - 7200000).toISOString(),
    author: {
      id: "user-2",
      full_name: "Mike Chen",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    },
  },

  {
    id: "post-6",
    workspace_id: "workspace-1",
    author_id: "user-1",
    content: "Happy Monday! 💪 Start your week strong with our productivity tips for social media managers. #MondayMotivation #Productivity",
    media: [
      {
        id: "media-post-6",
        type: "image",
        url: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b",
        thumbnail_url: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400",
        alt_text: "Productivity tips",
        width: 1200,
        height: 800,
        duration_seconds: null,
      },
    ],
    poll: null,
    link_preview: null,
    type: "image",
    platforms: ["instagram", "linkedin", "facebook"],
    platform_settings: [
      {
        platform: "instagram",
        account_id: "account-3",
        content_override: null,
        first_comment: "Save this for later! 🔖",
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "linkedin",
        account_id: "account-4",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "facebook",
        account_id: "account-5",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now + 259200000).toISOString(), // 3 days from now (Monday)
    published_at: null,
    status: "scheduled",
    hashtags: ["MondayMotivation", "Productivity"],
    mentions: [],
    tags: ["motivation", "tips"],
    approval_status: "approved",
    approved_by: "user-2",
    approved_at: new Date(now - 172800000).toISOString(),
    assigned_to: "user-1",
    engagement: null,
    is_pinned: false,
    template_id: "template-1",
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 259200000).toISOString(),
    updated_at: new Date(now - 172800000).toISOString(),
    author: {
      id: "user-1",
      full_name: "Sarah Johnson",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    },
  },

  // Draft posts
  {
    id: "post-7",
    workspace_id: "workspace-1",
    author_id: "user-1",
    content: "Working on something exciting... 👀 Stay tuned for a big announcement next week! #ComingSoon",
    media: [],
    poll: null,
    link_preview: null,
    type: "text",
    platforms: ["twitter", "instagram", "linkedin"],
    platform_settings: [],
    scheduled_for: null,
    published_at: null,
    status: "draft",
    hashtags: ["ComingSoon"],
    mentions: [],
    tags: ["announcement", "teaser"],
    approval_status: "pending",
    approved_by: null,
    approved_at: null,
    assigned_to: "user-1",
    engagement: null,
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 7200000).toISOString(),
    updated_at: new Date(now - 3600000).toISOString(),
    author: {
      id: "user-1",
      full_name: "Sarah Johnson",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    },
  },

  {
    id: "post-8",
    workspace_id: "workspace-1",
    author_id: "user-2",
    content: "Check out our latest case study on how @CompanyX increased their engagement by 300% using our platform! 📈",
    media: [],
    poll: null,
    link_preview: {
      url: "https://chatsian.com/case-studies/company-x",
      title: "Case Study: 300% Engagement Increase",
      description: "Learn how Company X transformed their social media strategy.",
      image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
      shortened_url: "https://chatsian.co/case-x",
    },
    type: "link",
    platforms: ["twitter", "linkedin"],
    platform_settings: [],
    scheduled_for: null,
    published_at: null,
    status: "draft",
    hashtags: ["CaseStudy", "Success"],
    mentions: ["@CompanyX"],
    tags: ["case-study", "customer"],
    approval_status: "needs_review",
    approved_by: null,
    approved_at: null,
    assigned_to: "user-2",
    engagement: null,
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 14400000).toISOString(),
    updated_at: new Date(now - 10800000).toISOString(),
    author: {
      id: "user-2",
      full_name: "Mike Chen",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    },
  },

  // More scheduled posts across next few weeks
  {
    id: "post-9",
    workspace_id: "workspace-1",
    author_id: "user-1",
    content: "Friday feeling! 🎉 What are your plans for the weekend? #FridayVibes #WeekendPlans",
    media: [
      {
        id: "media-post-9",
        type: "image",
        url: "https://images.unsplash.com/photo-1533158326339-7f3cf2404354",
        thumbnail_url: "https://images.unsplash.com/photo-1533158326339-7f3cf2404354?w=400",
        alt_text: "Weekend vibes",
        width: 1200,
        height: 800,
        duration_seconds: null,
      },
    ],
    poll: null,
    link_preview: null,
    type: "image",
    platforms: ["instagram", "twitter", "threads"],
    platform_settings: [
      {
        platform: "instagram",
        account_id: "account-3",
        content_override: null,
        first_comment: "Tag someone you're spending the weekend with! 👥",
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "twitter",
        account_id: "account-1",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "threads",
        account_id: "account-8",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now + 432000000).toISOString(), // 5 days from now
    published_at: null,
    status: "scheduled",
    hashtags: ["FridayVibes", "WeekendPlans"],
    mentions: [],
    tags: ["engagement", "community"],
    approval_status: "approved",
    approved_by: "user-2",
    approved_at: new Date(now - 86400000).toISOString(),
    assigned_to: "user-1",
    engagement: null,
    is_pinned: false,
    template_id: "template-2",
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 172800000).toISOString(),
    updated_at: new Date(now - 86400000).toISOString(),
    author: {
      id: "user-1",
      full_name: "Sarah Johnson",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    },
  },

  {
    id: "post-10",
    workspace_id: "workspace-1",
    author_id: "user-2",
    content: "Webinar alert! 🎓 Join us next Tuesday for a deep dive into social media analytics. Register now! #Webinar #Analytics",
    media: [
      {
        id: "media-post-10",
        type: "image",
        url: "https://images.unsplash.com/photo-1591115765373-5207764f72e7",
        thumbnail_url: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=400",
        alt_text: "Webinar announcement",
        width: 1200,
        height: 630,
        duration_seconds: null,
      },
    ],
    poll: null,
    link_preview: {
      url: "https://chatsian.com/webinars/analytics-masterclass",
      title: "Social Media Analytics Masterclass",
      description: "Learn to analyze and optimize your social media performance.",
      image_url: "https://images.unsplash.com/photo-1591115765373-5207764f72e7",
      shortened_url: "https://chatsian.co/webinar-analytics",
    },
    type: "link",
    platforms: ["linkedin", "twitter", "facebook"],
    platform_settings: [
      {
        platform: "linkedin",
        account_id: "account-4",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "twitter",
        account_id: "account-1",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
      {
        platform: "facebook",
        account_id: "account-5",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now + 604800000).toISOString(), // 7 days from now
    published_at: null,
    status: "scheduled",
    hashtags: ["Webinar", "Analytics"],
    mentions: [],
    tags: ["event", "education"],
    approval_status: "approved",
    approved_by: "user-1",
    approved_at: new Date(now - 259200000).toISOString(),
    assigned_to: "user-2",
    engagement: null,
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 432000000).toISOString(),
    updated_at: new Date(now - 259200000).toISOString(),
    author: {
      id: "user-2",
      full_name: "Mike Chen",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    },
  },

  // Add a failed post
  {
    id: "post-11",
    workspace_id: "workspace-1",
    author_id: "user-1",
    content: "Our holiday sale starts today! 🎁 Get 50% off all plans. Use code HOLIDAY50 #Sale #LimitedOffer",
    media: [
      {
        id: "media-post-11",
        type: "image",
        url: "https://images.unsplash.com/photo-1607083206325-cad1daa5d77c",
        thumbnail_url: "https://images.unsplash.com/photo-1607083206325-cad1daa5d77c?w=400",
        alt_text: "Holiday sale banner",
        width: 1200,
        height: 630,
        duration_seconds: null,
      },
    ],
    poll: null,
    link_preview: null,
    type: "image",
    platforms: ["twitter", "facebook", "instagram"],
    platform_settings: [
      {
        platform: "twitter",
        account_id: "account-1",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "tw-99887",
        platform_url: "https://twitter.com/chatsian/status/99887",
        published_at: new Date(now - 518400000).toISOString(),
        status: "published",
        error_message: null,
      },
      {
        platform: "facebook",
        account_id: "account-5",
        content_override: null,
        first_comment: null,
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "failed",
        error_message: "Authentication expired. Please reconnect your Facebook account.",
      },
      {
        platform: "instagram",
        account_id: "account-3",
        content_override: null,
        first_comment: "Link in bio! 🔗",
        thread_tweets: null,
        location_tag: null,
        tagged_users: [],
        platform_post_id: "ig-77665",
        platform_url: "https://instagram.com/p/77665",
        published_at: new Date(now - 518400000).toISOString(),
        status: "published",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now - 518400000).toISOString(), // 6 days ago
    published_at: new Date(now - 518400000).toISOString(),
    status: "failed", // Failed on one platform
    hashtags: ["Sale", "LimitedOffer"],
    mentions: [],
    tags: ["promotion", "sale"],
    approval_status: "approved",
    approved_by: "user-2",
    approved_at: new Date(now - 604800000).toISOString(),
    assigned_to: "user-1",
    engagement: {
      likes: 123,
      comments: 15,
      shares: 8,
      saves: 34,
      impressions: 3210,
      reach: 2340,
      clicks: 189,
      engagement_rate: 5.7,
    },
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 691200000).toISOString(),
    updated_at: new Date(now - 518400000).toISOString(),
    author: {
      id: "user-1",
      full_name: "Sarah Johnson",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    },
  },

  // Thread post example
  {
    id: "post-12",
    workspace_id: "workspace-1",
    author_id: "user-2",
    content: "🧵 Thread: 5 Tips for Better Social Media Engagement\n\n1/ First, consistency is key. Post regularly to stay top of mind...",
    media: [],
    poll: null,
    link_preview: null,
    type: "thread",
    platforms: ["twitter"],
    platform_settings: [
      {
        platform: "twitter",
        account_id: "account-1",
        content_override: null,
        first_comment: null,
        thread_tweets: [
          "🧵 Thread: 5 Tips for Better Social Media Engagement\n\n1/ First, consistency is key. Post regularly to stay top of mind...",
          "2/ Know your audience. Use analytics to understand what content resonates most with your followers.",
          "3/ Engage back! Respond to comments and messages promptly to build a community.",
          "4/ Use visuals. Posts with images or videos get significantly more engagement.",
          "5/ Analyze and adapt. Review your metrics regularly and adjust your strategy based on what works.",
        ],
        location_tag: null,
        tagged_users: [],
        platform_post_id: null,
        platform_url: null,
        published_at: null,
        status: "scheduled",
        error_message: null,
      },
    ],
    scheduled_for: new Date(now + 345600000).toISOString(), // 4 days from now
    published_at: null,
    status: "scheduled",
    hashtags: ["SocialMediaTips", "Thread"],
    mentions: [],
    tags: ["tips", "education", "thread"],
    approval_status: "approved",
    approved_by: "user-1",
    approved_at: new Date(now - 43200000).toISOString(),
    assigned_to: "user-2",
    engagement: null,
    is_pinned: false,
    template_id: null,
    parent_post_id: null,
    metadata: {},
    created_at: new Date(now - 86400000).toISOString(),
    updated_at: new Date(now - 43200000).toISOString(),
    author: {
      id: "user-2",
      full_name: "Mike Chen",
      avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    },
  },
];

// Helper functions
export function getPostsByStatus(status: string) {
  return mockPosts.filter((post) => post.status === status);
}

export function getPostsByDateRange(startDate: Date, endDate: Date) {
  return mockPosts.filter((post) => {
    if (!post.scheduled_for && !post.published_at) return false;
    const postDate = new Date(post.scheduled_for || post.published_at || "");
    return postDate >= startDate && postDate <= endDate;
  });
}

export function getPostsByPlatform(platform: string) {
  return mockPosts.filter((post) => post.platforms.includes(platform as any));
}
