import type { ListeningStreamItem } from "../zod-schemas";

// ============================================================================
// SOCIAL SIGNALS / LISTENING STREAM ITEMS
// Platform-specific mock data for crisis incidents
// ============================================================================

export const mockSocialSignals: ListeningStreamItem[] = [
  // Twitter/X Posts - Negative sentiment
  {
    id: "signal-twitter-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "twitter",
    platformPostId: "1234567890123456789",
    platformUrl: "https://twitter.com/user/status/1234567890123456789",
    authorName: "Sarah Johnson",
    authorHandle: "@sarahjohnson",
    authorProfileUrl: "https://twitter.com/sarahjohnson",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=sarahjohnson",
    authorVerified: false,
    content: "This is absolutely unacceptable! I've been waiting for my order for 3 weeks now. The shipping delay is ridiculous and customer service won't even respond to my emails. #frustrated #terrible",
    contentPreview: "This is absolutely unacceptable! I've been waiting for my order for 3 weeks now...",
    mediaUrls: [],
    hashtags: ["frustrated", "terrible"],
    mentions: [],
    engagementCount: 82,
    likesCount: 47,
    commentsCount: 12,
    sharesCount: 23,
    viewsCount: 1200,
    followerCount: 3400,
    authorFollowerCount: 3400,
    isInfluencer: false,
    sentiment: "negative",
    sentimentScore: -0.85,
    sentimentConfidence: 0.92,
    sentimentKeywords: ["unacceptable", "ridiculous", "frustrated", "terrible"],
    emotions: {
      anger: 0.75,
      frustration: 0.65,
      disappointment: 0.45,
    },
    categories: ["complaint", "shipping"],
    matchedKeywords: ["shipping delay", "customer service"],
    isRead: false,
    isStarred: false,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T11:45:00Z",
    discoveredAt: "2025-11-22T11:46:00Z",
    potentialReach: 8500,
    actualReach: 1200,
    engagementScore: 6.8,
    priority: "high",
    metadata: {},
    createdAt: "2025-11-22T11:46:00Z",
  },
  {
    id: "signal-twitter-2",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "twitter",
    platformPostId: "1234567890123456790",
    platformUrl: "https://twitter.com/user/status/1234567890123456790",
    authorName: "Mike Chen",
    authorHandle: "@mikechen",
    authorProfileUrl: "https://twitter.com/mikechen",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=mikechen",
    authorVerified: true,
    content: "Really disappointed with the quality of service lately. Orders delayed, no communication, terrible experience overall. Not what I expected from this brand.",
    contentPreview: "Really disappointed with the quality of service lately. Orders delayed...",
    mediaUrls: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa"],
    hashtags: [],
    mentions: [],
    engagementCount: 156,
    likesCount: 89,
    commentsCount: 34,
    sharesCount: 33,
    viewsCount: 4500,
    followerCount: 12500,
    authorFollowerCount: 12500,
    isInfluencer: true,
    sentiment: "negative",
    sentimentScore: -0.72,
    sentimentConfidence: 0.88,
    sentimentKeywords: ["disappointed", "delayed", "terrible"],
    emotions: {
      disappointment: 0.70,
      frustration: 0.45,
    },
    categories: ["complaint", "quality"],
    matchedKeywords: ["delayed", "terrible experience"],
    isRead: false,
    isStarred: true,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T11:30:00Z",
    discoveredAt: "2025-11-22T11:31:00Z",
    potentialReach: 31250,
    actualReach: 4500,
    engagementScore: 3.5,
    priority: "critical",
    metadata: {},
    createdAt: "2025-11-22T11:31:00Z",
  },
  {
    id: "signal-twitter-3",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "twitter",
    platformPostId: "1234567890123456791",
    platformUrl: "https://twitter.com/user/status/1234567890123456791",
    authorName: "Jessica Martinez",
    authorHandle: "@jessicam",
    authorProfileUrl: "https://twitter.com/jessicam",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=jessicam",
    authorVerified: false,
    content: "Has anyone else experienced shipping delays? I'm on week 3 of waiting. Getting really frustrated here.",
    contentPreview: "Has anyone else experienced shipping delays? I'm on week 3 of waiting...",
    mediaUrls: [],
    hashtags: [],
    mentions: [],
    engagementCount: 45,
    likesCount: 23,
    commentsCount: 18,
    sharesCount: 4,
    viewsCount: 890,
    followerCount: 1200,
    authorFollowerCount: 1200,
    isInfluencer: false,
    sentiment: "negative",
    sentimentScore: -0.58,
    sentimentConfidence: 0.85,
    sentimentKeywords: ["delays", "frustrated", "waiting"],
    emotions: {
      frustration: 0.60,
      impatience: 0.45,
    },
    categories: ["inquiry", "complaint", "shipping"],
    matchedKeywords: ["shipping delays"],
    isRead: false,
    isStarred: false,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T11:15:00Z",
    discoveredAt: "2025-11-22T11:16:00Z",
    potentialReach: 3000,
    actualReach: 890,
    engagementScore: 5.1,
    priority: "medium",
    metadata: {},
    createdAt: "2025-11-22T11:16:00Z",
  },

  // Instagram Posts
  {
    id: "signal-instagram-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "instagram",
    platformPostId: "3045678901234567890",
    platformUrl: "https://instagram.com/p/AbCdEfGhIjK",
    authorName: "Emily Rodriguez",
    authorHandle: "@emily_rodriguez",
    authorProfileUrl: "https://instagram.com/emily_rodriguez",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=emilyrodriguez",
    authorVerified: false,
    content: "Absolutely love this product! Best purchase I've made all year. Customer service was amazing and shipping was super fast! 😍✨ #amazing #bestbrand #loveit",
    contentPreview: "Absolutely love this product! Best purchase I've made all year...",
    mediaUrls: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f",
    ],
    hashtags: ["amazing", "bestbrand", "loveit"],
    mentions: [],
    engagementCount: 1332,
    likesCount: 1245,
    commentsCount: 87,
    sharesCount: 0,
    viewsCount: undefined,
    followerCount: 125000,
    authorFollowerCount: 125000,
    isInfluencer: true,
    sentiment: "positive",
    sentimentScore: 0.92,
    sentimentConfidence: 0.96,
    sentimentKeywords: ["love", "amazing", "best"],
    emotions: {
      joy: 0.85,
      satisfaction: 0.80,
      excitement: 0.75,
    },
    categories: ["praise", "review"],
    matchedKeywords: ["amazing", "best"],
    isRead: false,
    isStarred: false,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T10:00:00Z",
    discoveredAt: "2025-11-22T10:05:00Z",
    potentialReach: 312500,
    actualReach: 45000,
    engagementScore: 1.07,
    priority: "low",
    metadata: {
      carouselIndex: 0,
      carouselTotal: 3,
    },
    createdAt: "2025-11-22T10:05:00Z",
  },
  {
    id: "signal-instagram-2",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "instagram",
    platformPostId: "3045678901234567891",
    platformUrl: "https://instagram.com/p/XyZaBcDeFgH",
    authorName: "David Kim",
    authorHandle: "@davidkim_official",
    authorProfileUrl: "https://instagram.com/davidkim_official",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=davidkim",
    authorVerified: true,
    content: "Not happy with my recent purchase 😞 The quality doesn't match what was advertised and it arrived damaged. Really expected better.",
    contentPreview: "Not happy with my recent purchase 😞 The quality doesn't match...",
    mediaUrls: ["https://images.unsplash.com/photo-1526738549149-8e07eca6c147"],
    hashtags: [],
    mentions: [],
    engagementCount: 456,
    likesCount: 342,
    commentsCount: 98,
    sharesCount: 16,
    viewsCount: undefined,
    followerCount: 45000,
    authorFollowerCount: 45000,
    isInfluencer: true,
    sentiment: "negative",
    sentimentScore: -0.68,
    sentimentConfidence: 0.90,
    sentimentKeywords: ["not happy", "damaged", "expected better"],
    emotions: {
      disappointment: 0.75,
      frustration: 0.50,
    },
    categories: ["complaint", "quality"],
    matchedKeywords: ["damaged", "quality"],
    isRead: false,
    isStarred: true,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T09:30:00Z",
    discoveredAt: "2025-11-22T09:35:00Z",
    potentialReach: 112500,
    actualReach: 23000,
    engagementScore: 1.98,
    priority: "high",
    metadata: {},
    createdAt: "2025-11-22T09:35:00Z",
  },

  // YouTube Videos
  {
    id: "signal-youtube-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "youtube",
    platformPostId: "dQw4w9WgXcQ",
    platformUrl: "https://youtube.com/watch?v=dQw4w9WgXcQ",
    authorName: "TechReviewer Pro",
    authorHandle: "@techreviewerpro",
    authorProfileUrl: "https://youtube.com/@techreviewerpro",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=techreviewerpro",
    authorVerified: true,
    content: "My Honest Review - Major Disappointment | Unboxing & First Impressions",
    contentPreview: "My Honest Review - Major Disappointment | Unboxing & First...",
    mediaUrls: ["https://images.unsplash.com/photo-1611162617474-5b21e879e113"],
    hashtags: ["review", "unboxing", "honest"],
    mentions: [],
    engagementCount: 401,
    likesCount: 245,
    commentsCount: 67,
    sharesCount: 89,
    viewsCount: 12500,
    followerCount: 234000,
    authorFollowerCount: 234000,
    isInfluencer: true,
    sentiment: "negative",
    sentimentScore: -0.62,
    sentimentConfidence: 0.87,
    sentimentKeywords: ["disappointment", "honest review"],
    emotions: {
      disappointment: 0.70,
      criticism: 0.55,
    },
    categories: ["review", "unboxing"],
    matchedKeywords: ["disappointment", "review"],
    isRead: false,
    isStarred: true,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T08:00:00Z",
    discoveredAt: "2025-11-22T08:15:00Z",
    potentialReach: 585000,
    actualReach: 12500,
    engagementScore: 3.2,
    priority: "critical",
    metadata: {
      duration: "5:32",
      thumbnailUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113",
      likes: 245,
      dislikes: 89,
      commentsSentiment: {
        positive: 20,
        neutral: 28,
        negative: 52,
      },
    },
    createdAt: "2025-11-22T08:15:00Z",
  },

  // TikTok Videos
  {
    id: "signal-tiktok-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "tiktok",
    platformPostId: "7123456789012345678",
    platformUrl: "https://tiktok.com/@user/video/7123456789012345678",
    authorName: "Unboxing Queen",
    authorHandle: "@unboxingqueen",
    authorProfileUrl: "https://tiktok.com/@unboxingqueen",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=unboxingqueen",
    authorVerified: true,
    content: "Unboxing disaster 😭 This is NOT what I ordered #fail #disappointed #scam",
    contentPreview: "Unboxing disaster 😭 This is NOT what I ordered...",
    mediaUrls: ["https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da"],
    hashtags: ["fail", "disappointed", "scam"],
    mentions: [],
    engagementCount: 55100,
    likesCount: 45200,
    commentsCount: 1200,
    sharesCount: 8900,
    viewsCount: 234000,
    followerCount: 2300000,
    authorFollowerCount: 2300000,
    isInfluencer: true,
    sentiment: "negative",
    sentimentScore: -0.82,
    sentimentConfidence: 0.94,
    sentimentKeywords: ["disaster", "disappointed", "scam", "fail"],
    emotions: {
      anger: 0.65,
      disappointment: 0.80,
      frustration: 0.70,
    },
    categories: ["complaint", "unboxing"],
    matchedKeywords: ["disaster", "fail", "scam"],
    isRead: false,
    isStarred: true,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-21T16:00:00Z",
    discoveredAt: "2025-11-21T16:30:00Z",
    potentialReach: 5750000,
    actualReach: 234000,
    engagementScore: 23.5,
    priority: "critical",
    metadata: {
      duration: "0:45",
      sound: "Original audio - @unboxingqueen",
      isViral: true,
      viralityScore: 10.4,
      trendingHashtags: ["#fail"],
    },
    createdAt: "2025-11-21T16:30:00Z",
  },

  // Facebook Posts
  {
    id: "signal-facebook-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "facebook",
    platformPostId: "10159123456789012",
    platformUrl: "https://facebook.com/user/posts/10159123456789012",
    authorName: "John Doe",
    authorHandle: "john.doe.123",
    authorProfileUrl: "https://facebook.com/john.doe.123",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=johndoe",
    authorVerified: false,
    content: "Has anyone else had issues with their customer service? Been on hold for 2 hours trying to track my order. This is getting ridiculous...",
    contentPreview: "Has anyone else had issues with their customer service? Been on hold...",
    mediaUrls: [],
    hashtags: [],
    mentions: [],
    engagementCount: 80,
    likesCount: 23,
    commentsCount: 45,
    sharesCount: 12,
    viewsCount: undefined,
    followerCount: 567,
    authorFollowerCount: 567,
    isInfluencer: false,
    sentiment: "negative",
    sentimentScore: -0.55,
    sentimentConfidence: 0.82,
    sentimentKeywords: ["issues", "ridiculous", "hold"],
    emotions: {
      frustration: 0.70,
      impatience: 0.60,
    },
    categories: ["complaint", "customer service"],
    matchedKeywords: ["customer service", "issues"],
    isRead: false,
    isStarred: false,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T10:30:00Z",
    discoveredAt: "2025-11-22T10:45:00Z",
    potentialReach: 1417,
    actualReach: 456,
    engagementScore: 17.5,
    priority: "medium",
    metadata: {
      privacy: "public",
      location: "New York, NY",
      topComment: {
        text: "Same here! Terrible experience with them lately...",
        reactions: 87,
      },
      threadSentiment: -0.78,
    },
    createdAt: "2025-11-22T10:45:00Z",
  },

  // Reddit Posts
  {
    id: "signal-reddit-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "reddit",
    platformPostId: "abc123xyz",
    platformUrl: "https://reddit.com/r/ProductReviews/comments/abc123xyz",
    authorName: "u/frustrated_customer",
    authorHandle: "frustrated_customer",
    authorProfileUrl: "https://reddit.com/user/frustrated_customer",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=reddituser",
    authorVerified: false,
    content: "[Discussion] Terrible experience with [Brand] - 3 weeks and counting\n\nI ordered 3 weeks ago and still nothing. Customer service won't respond to emails or calls. This is absolutely unacceptable for a company this size. Anyone else having similar issues?",
    contentPreview: "[Discussion] Terrible experience with [Brand] - 3 weeks and counting...",
    mediaUrls: [],
    hashtags: [],
    mentions: [],
    engagementCount: 490,
    likesCount: 245,
    commentsCount: 156,
    sharesCount: 89,
    viewsCount: 3400,
    followerCount: undefined,
    authorFollowerCount: 1234,
    isInfluencer: false,
    sentiment: "negative",
    sentimentScore: -0.88,
    sentimentConfidence: 0.91,
    sentimentKeywords: ["terrible", "unacceptable", "issues"],
    emotions: {
      anger: 0.75,
      frustration: 0.85,
    },
    categories: ["complaint", "discussion"],
    matchedKeywords: ["terrible", "unacceptable"],
    isRead: false,
    isStarred: true,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-21T20:00:00Z",
    discoveredAt: "2025-11-21T20:15:00Z",
    potentialReach: 125000,
    actualReach: 3400,
    engagementScore: 14.4,
    priority: "high",
    metadata: {
      subreddit: "r/ProductReviews",
      upvotes: 245,
      downvotes: 89,
      upvoteRatio: 0.73,
      awards: 2,
      topComments: [
        { text: "I had the same issue last month...", score: 89 },
        { text: "You should contact your credit card company", score: 67 },
      ],
      threadTone: "highly_critical",
    },
    createdAt: "2025-11-21T20:15:00Z",
  },

  // LinkedIn Posts
  {
    id: "signal-linkedin-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "linkedin",
    platformPostId: "activity:6987654321098765432",
    platformUrl: "https://linkedin.com/posts/activity-6987654321098765432",
    authorName: "Sarah Thompson",
    authorHandle: "sarah-thompson",
    authorProfileUrl: "https://linkedin.com/in/sarah-thompson",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=sarahthompson",
    authorVerified: false,
    content: "Excited to share our positive experience with [Brand]! Their customer service team went above and beyond to ensure our B2B order was delivered on time. Highly recommend for enterprise needs. #B2B #CustomerService #Excellence",
    contentPreview: "Excited to share our positive experience with [Brand]! Their customer...",
    mediaUrls: [],
    hashtags: ["B2B", "CustomerService", "Excellence"],
    mentions: [],
    engagementCount: 65,
    likesCount: 45,
    commentsCount: 12,
    sharesCount: 8,
    viewsCount: 2300,
    followerCount: 8900,
    authorFollowerCount: 8900,
    isInfluencer: false,
    sentiment: "positive",
    sentimentScore: 0.78,
    sentimentConfidence: 0.89,
    sentimentKeywords: ["excited", "positive", "highly recommend"],
    emotions: {
      satisfaction: 0.80,
      professionalism: 0.85,
    },
    categories: ["endorsement", "b2b"],
    matchedKeywords: ["positive experience", "recommend"],
    isRead: false,
    isStarred: false,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-22T09:00:00Z",
    discoveredAt: "2025-11-22T09:10:00Z",
    potentialReach: 22250,
    actualReach: 2300,
    engagementScore: 2.8,
    priority: "low",
    metadata: {
      title: "Senior Marketing Manager at TechCorp",
      company: "TechCorp",
      connectionDegree: 2,
      professionalContext: "b2b_endorsement",
    },
    createdAt: "2025-11-22T09:10:00Z",
  },

  // Trustpilot Review
  {
    id: "signal-trustpilot-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "trustpilot",
    platformPostId: "review-123456789",
    platformUrl: "https://trustpilot.com/reviews/123456789",
    authorName: "John S.",
    authorHandle: "john-s-verified",
    authorProfileUrl: "https://trustpilot.com/users/john-s-verified",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=johns",
    authorVerified: true,
    content: "Worst experience ever. Ordered 3 weeks ago, still haven't received my package. Customer service is completely unresponsive. Multiple emails and calls - nothing. Save your money and shop elsewhere.",
    contentPreview: "Worst experience ever. Ordered 3 weeks ago, still haven't received...",
    mediaUrls: [],
    hashtags: [],
    mentions: [],
    engagementCount: 23,
    likesCount: 0,
    commentsCount: 0,
    sharesCount: 0,
    viewsCount: undefined,
    followerCount: undefined,
    authorFollowerCount: 0,
    isInfluencer: false,
    sentiment: "negative",
    sentimentScore: -0.95,
    sentimentConfidence: 0.97,
    sentimentKeywords: ["worst", "unresponsive", "save your money"],
    emotions: {
      anger: 0.85,
      frustration: 0.90,
      disappointment: 0.80,
    },
    categories: ["review", "complaint"],
    matchedKeywords: ["worst", "unresponsive"],
    isRead: false,
    isStarred: true,
    isArchived: false,
    repliedTo: false,
    convertedToConversation: false,
    postedAt: "2025-11-21T14:00:00Z",
    discoveredAt: "2025-11-21T14:30:00Z",
    potentialReach: 5000,
    actualReach: 450,
    engagementScore: 5.1,
    priority: "critical",
    metadata: {
      rating: 1,
      maxRating: 5,
      verifiedPurchase: true,
      helpfulCount: 23,
      companyResponded: false,
      averageResponseTime: "2 days",
    },
    createdAt: "2025-11-21T14:30:00Z",
  },

  // Google My Business Review
  {
    id: "signal-google-1",
    streamId: "stream-1",
    workspaceId: "workspace-1",
    platform: "google-my-business",
    platformPostId: "gmb-review-987654321",
    platformUrl: "https://google.com/maps/reviews/987654321",
    authorName: "Maria Garcia",
    authorHandle: "maria-garcia",
    authorProfileUrl: "https://google.com/maps/contrib/maria-garcia",
    authorAvatarUrl: "https://i.pravatar.cc/150?u=mariagarcia",
    authorVerified: true,
    content: "Excellent service! Quick delivery, product exactly as described, and the team was very responsive to my questions. Will definitely order again!",
    contentPreview: "Excellent service! Quick delivery, product exactly as described...",
    mediaUrls: ["https://images.unsplash.com/photo-1560393464-5c69a73c5770"],
    hashtags: [],
    mentions: [],
    engagementCount: 8,
    likesCount: 8,
    commentsCount: 0,
    sharesCount: 0,
    viewsCount: undefined,
    followerCount: undefined,
    authorFollowerCount: 0,
    isInfluencer: false,
    sentiment: "positive",
    sentimentScore: 0.88,
    sentimentConfidence: 0.93,
    sentimentKeywords: ["excellent", "quick", "responsive"],
    emotions: {
      satisfaction: 0.90,
      joy: 0.70,
    },
    categories: ["review", "praise"],
    matchedKeywords: ["excellent", "responsive"],
    isRead: false,
    isStarred: false,
    isArchived: false,
    repliedTo: true,
    convertedToConversation: false,
    postedAt: "2025-11-20T11:00:00Z",
    discoveredAt: "2025-11-20T11:15:00Z",
    potentialReach: 1200,
    actualReach: 340,
    engagementScore: 2.4,
    priority: "low",
    metadata: {
      rating: 5,
      maxRating: 5,
      verifiedPurchase: true,
      companyResponded: true,
      responseText: "Thank you for your kind words, Maria!",
      responseTime: "2 hours",
    },
    createdAt: "2025-11-20T11:15:00Z",
  },
];

// Map social signals to incidents
export const incidentSocialSignalsMap: Record<string, string[]> = {
  "incident-1": [
    "signal-twitter-1",
    "signal-twitter-2",
    "signal-twitter-3",
    "signal-instagram-2",
    "signal-youtube-1",
    "signal-tiktok-1",
    "signal-facebook-1",
    "signal-reddit-1",
    "signal-trustpilot-1",
  ],
  "incident-2": [],
  "incident-3": [],
};

// Helper function to get signals for an incident
export function getSignalsForIncident(incidentId: string): ListeningStreamItem[] {
  const signalIds = incidentSocialSignalsMap[incidentId] || [];
  return mockSocialSignals.filter((signal) => signalIds.includes(signal.id));
}

// Helper function to get signal counts by platform
export function getSignalCountsByPlatform(incidentId: string): Record<string, number> {
  const signals = getSignalsForIncident(incidentId);
  const counts: Record<string, number> = {};

  signals.forEach((signal) => {
    counts[signal.platform] = (counts[signal.platform] || 0) + 1;
  });

  return counts;
}

// Helper function to get sentiment distribution
export function getSentimentDistribution(incidentId: string) {
  const signals = getSignalsForIncident(incidentId);
  const distribution = {
    positive: 0,
    neutral: 0,
    negative: 0,
  };

  signals.forEach((signal) => {
    if (signal.sentiment) {
      distribution[signal.sentiment]++;
    }
  });

  return distribution;
}
