import Foundation

class MockListening {
    static let shared = MockListening()

    let queries: [ListeningQuery] = [
        ListeningQuery(
            id: "query-1",
            workspaceId: "workspace-1",
            name: "Brand Mentions",
            description: "Track all mentions of our brand across social media",
            queryType: "brand",
            icon: "🏢",
            keywords: ["Chatsian", "chatsian"],
            mentions: ["@Chatsian"],
            platforms: [.twitter, .instagram, .linkedin, .facebook],
            isActive: true,
            isStarred: true,
            alertsEnabled: true,
            totalMentions: 2847,
            mentionCount24h: 143,
            mentionCount7d: 892,
            lastMentionAt: Date().addingTimeInterval(-1800),
            color: "#3B82F6",
            createdAt: Date().addingTimeInterval(-86400 * 60),
            updatedAt: Date().addingTimeInterval(-3600)
        ),
        ListeningQuery(
            id: "query-2",
            workspaceId: "workspace-1",
            name: "Customer Support",
            description: "Monitor support-related keywords and issues",
            queryType: "keyword",
            icon: "🎧",
            keywords: ["help", "support", "issue", "problem"],
            platforms: [.twitter, .facebook],
            isActive: true,
            alertsEnabled: true,
            totalMentions: 1234,
            mentionCount24h: 67,
            mentionCount7d: 428,
            lastMentionAt: Date().addingTimeInterval(-3600),
            color: "#EF4444",
            createdAt: Date().addingTimeInterval(-86400 * 45),
            updatedAt: Date().addingTimeInterval(-7200)
        ),
        ListeningQuery(
            id: "query-3",
            workspaceId: "workspace-1",
            name: "Competitor Analysis",
            description: "Track competitor mentions and activities",
            queryType: "competitor",
            icon: "🔍",
            keywords: ["CompetitorA", "CompetitorB"],
            mentions: ["@CompetitorA", "@CompetitorB"],
            platforms: [.twitter, .linkedin],
            isActive: true,
            totalMentions: 5623,
            mentionCount24h: 287,
            mentionCount7d: 1756,
            lastMentionAt: Date().addingTimeInterval(-900),
            color: "#8B5CF6",
            createdAt: Date().addingTimeInterval(-86400 * 30),
            updatedAt: Date().addingTimeInterval(-14400)
        ),
        ListeningQuery(
            id: "query-4",
            workspaceId: "workspace-1",
            name: "Product Launch",
            description: "Monitor reactions to our latest product launch",
            queryType: "topic",
            icon: "🚀",
            keywords: ["NewProduct2024", "ProductLaunch"],
            hashtags: ["#NewProduct2024", "#Innovation"],
            platforms: [.twitter, .instagram, .linkedin],
            isActive: true,
            isStarred: true,
            totalMentions: 8934,
            mentionCount24h: 456,
            mentionCount7d: 2834,
            lastMentionAt: Date().addingTimeInterval(-600),
            color: "#10B981",
            createdAt: Date().addingTimeInterval(-86400 * 7),
            updatedAt: Date().addingTimeInterval(-1800)
        )
    ]

    let mentions: [ListeningMention] = [
        ListeningMention(
            id: "mention-1",
            queryId: "query-1",
            workspaceId: "workspace-1",
            platform: .twitter,
            platformPostId: "123456789",
            platformPostUrl: "https://twitter.com/user/status/123456789",
            authorPlatformId: "user-123",
            authorUsername: "techinfluencer",
            authorDisplayName: "Tech Influencer",
            authorAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=tech",
            authorVerified: true,
            authorFollowerCount: 125000,
            authorBio: "Technology reviewer and content creator",
            content: "Just tried @Chatsian and I'm blown away! This is the future of social media management. 🚀 Highly recommend checking it out! #SocialMediaTools #ProductivityHack",
            contentPreview: "Just tried @Chatsian and I'm blown away! This is the future of social media management...",
            mentionType: "direct_mention",
            matchedKeywords: ["Chatsian"],
            matchedMentions: ["@Chatsian"],
            matchedHashtags: ["#SocialMediaTools", "#ProductivityHack"],
            hasMedia: true,
            mediaCount: 2,
            mediaUrls: ["https://picsum.photos/800/600?random=10"],
            likesCount: 1523,
            sharesCount: 342,
            commentsCount: 89,
            viewsCount: 45600,
            engagementScore: 1954,
            potentialReach: 375000,
            sentiment: .positive,
            sentimentScore: 0.92,
            sentimentConfidence: 0.95,
            sentimentKeywords: ["blown away", "future", "highly recommend"],
            priority: .high,
            isViral: true,
            isInfluencer: true,
            language: "en",
            publishedAt: Date().addingTimeInterval(-7200),
            capturedAt: Date().addingTimeInterval(-7000)
        ),
        ListeningMention(
            id: "mention-2",
            queryId: "query-2",
            workspaceId: "workspace-1",
            platform: .twitter,
            platformPostId: "987654321",
            platformPostUrl: "https://twitter.com/user/status/987654321",
            authorPlatformId: "user-456",
            authorUsername: "frustrated_user",
            authorDisplayName: "Customer Joe",
            authorAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=joe",
            authorFollowerCount: 342,
            content: "Having trouble logging into @Chatsian for the past hour. Support team, please help! 😤 #NeedHelp",
            contentPreview: "Having trouble logging into @Chatsian for the past hour. Support team, please help!",
            mentionType: "keyword_match",
            matchedKeywords: ["help", "support"],
            matchedMentions: ["@Chatsian"],
            matchedHashtags: ["#NeedHelp"],
            likesCount: 12,
            commentsCount: 3,
            sharesCount: 1,
            engagementScore: 16,
            potentialReach: 1200,
            sentiment: .negative,
            sentimentScore: -0.78,
            sentimentConfidence: 0.88,
            sentimentKeywords: ["trouble", "frustrated"],
            priority: .critical,
            isRead: true,
            language: "en",
            publishedAt: Date().addingTimeInterval(-5400),
            capturedAt: Date().addingTimeInterval(-5300)
        ),
        ListeningMention(
            id: "mention-3",
            queryId: "query-4",
            workspaceId: "workspace-1",
            platform: .instagram,
            platformPostId: "ig_123456",
            platformPostUrl: "https://instagram.com/p/ig_123456",
            authorPlatformId: "ig_user_789",
            authorUsername: "designerlife",
            authorDisplayName: "Emma Designer",
            authorAvatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma",
            authorVerified: true,
            authorFollowerCount: 89000,
            authorBio: "UI/UX Designer | Creative Director",
            content: "The new product from Chatsian is absolutely stunning! Love the attention to detail 💎✨ #NewProduct2024 #Design",
            contentPreview: "The new product from Chatsian is absolutely stunning! Love the attention to detail 💎✨",
            mentionType: "hashtag_match",
            matchedKeywords: ["NewProduct2024", "Chatsian"],
            matchedHashtags: ["#NewProduct2024", "#Design"],
            hasMedia: true,
            mediaCount: 4,
            mediaUrls: ["https://picsum.photos/800/800?random=11", "https://picsum.photos/800/800?random=12"],
            likesCount: 3421,
            commentsCount: 156,
            sharesCount: 89,
            engagementScore: 3666,
            potentialReach: 267000,
            sentiment: .positive,
            sentimentScore: 0.88,
            sentimentConfidence: 0.91,
            sentimentKeywords: ["stunning", "love", "attention to detail"],
            priority: .high,
            isInfluencer: true,
            language: "en",
            publishedAt: Date().addingTimeInterval(-14400),
            capturedAt: Date().addingTimeInterval(-14300)
        )
    ]
}
