import type {
  CrisisIncident,
  CrisisDetectionRule,
  StatusComponent,
  StatusPageUpdate,
  MessageSentiment,
} from "../zod-schemas";

// ============================================================================
// CRISIS INCIDENTS
// ============================================================================

export const mockCrisisIncidents: CrisisIncident[] = [
  {
    id: "incident-1",
    workspaceId: "workspace-1",
    title: "Negative Sentiment Spike on Twitter",
    description: "Unusual spike in negative sentiment detected across Twitter platform related to recent product launch.",
    severity: "high",
    status: "investigating",
    detectionType: "sentiment_spike",
    detectionRuleId: "rule-1",
    detectionConfig: {
      negative_count: 47,
      time_window_minutes: 60,
      threshold: 20,
    },
    platforms: ["twitter"],
    negativeMessageCount: 47,
    totalMessageCount: 65,
    averageSentimentScore: -0.65,
    detectedAt: "2025-11-22T10:30:00Z",
    acknowledgedAt: "2025-11-22T10:45:00Z",
    acknowledgedBy: "user-1",
    relatedConversationIds: ["conv-1", "conv-2", "conv-3"],
    relatedMessageIds: ["msg-1", "msg-2", "msg-3"],
    statusUpdates: [
      {
        timestamp: "2025-11-22T10:30:00Z",
        from: "detected",
        to: "acknowledged",
        user_id: "user-1",
      },
      {
        timestamp: "2025-11-22T10:45:00Z",
        from: "acknowledged",
        to: "investigating",
        user_id: "user-1",
      },
    ],
    resolutionActions: [],
    estimatedReach: 150000,
    impactNotes: "Primarily affecting US users, related to shipping delays",
    metadata: {},
    createdAt: "2025-11-22T10:30:00Z",
    updatedAt: "2025-11-22T10:45:00Z",
  },
  {
    id: "incident-2",
    workspaceId: "workspace-1",
    title: "Security Concern Keyword Detected",
    description: "Multiple mentions of 'data breach' detected across social platforms.",
    severity: "critical",
    status: "resolved",
    detectionType: "keyword_match",
    detectionRuleId: "rule-2",
    detectionConfig: {
      keywords: ["data breach", "hack"],
      matched: "data breach",
    },
    platforms: ["twitter", "facebook"],
    negativeMessageCount: 12,
    totalMessageCount: 12,
    averageSentimentScore: -0.85,
    detectedAt: "2025-11-20T14:15:00Z",
    acknowledgedAt: "2025-11-20T14:20:00Z",
    acknowledgedBy: "user-2",
    resolvedAt: "2025-11-20T18:30:00Z",
    resolvedBy: "user-2",
    resolutionNotes: "False alarm - users discussing industry news, not our company. Clarification posted on all platforms.",
    resolutionActions: [
      {
        timestamp: "2025-11-20T15:00:00Z",
        action: "Posted clarification statement on Twitter",
        user_id: "user-2",
      },
      {
        timestamp: "2025-11-20T15:30:00Z",
        action: "Updated status page with incident details",
        user_id: "user-2",
      },
      {
        timestamp: "2025-11-20T18:30:00Z",
        action: "Confirmed resolution with security team",
        user_id: "user-2",
      },
    ],
    relatedConversationIds: ["conv-4", "conv-5"],
    relatedMessageIds: ["msg-10", "msg-11", "msg-12"],
    statusUpdates: [
      {
        timestamp: "2025-11-20T14:15:00Z",
        from: "detected",
        to: "acknowledged",
        user_id: "user-2",
      },
      {
        timestamp: "2025-11-20T14:20:00Z",
        from: "acknowledged",
        to: "investigating",
        user_id: "user-2",
      },
      {
        timestamp: "2025-11-20T15:00:00Z",
        from: "investigating",
        to: "resolving",
        user_id: "user-2",
      },
      {
        timestamp: "2025-11-20T18:30:00Z",
        from: "resolving",
        to: "resolved",
        user_id: "user-2",
      },
    ],
    estimatedReach: 75000,
    impactNotes: "Limited impact - clarification successfully prevented escalation",
    metadata: {},
    createdAt: "2025-11-20T14:15:00Z",
    updatedAt: "2025-11-20T18:30:00Z",
  },
  {
    id: "incident-3",
    workspaceId: "workspace-1",
    title: "Instagram Engagement Drop",
    description: "Significant decrease in engagement detected on Instagram posts.",
    severity: "medium",
    status: "acknowledged",
    detectionType: "volume_spike",
    detectionConfig: {
      metric: "engagement_rate",
      drop_percentage: 65,
    },
    platforms: ["instagram"],
    negativeMessageCount: 0,
    totalMessageCount: 0,
    detectedAt: "2025-11-22T08:00:00Z",
    acknowledgedAt: "2025-11-22T09:00:00Z",
    acknowledgedBy: "user-3",
    relatedConversationIds: [],
    relatedMessageIds: [],
    statusUpdates: [
      {
        timestamp: "2025-11-22T08:00:00Z",
        from: "detected",
        to: "acknowledged",
        user_id: "user-3",
      },
    ],
    resolutionActions: [],
    estimatedReach: 50000,
    impactNotes: "Investigating possible algorithm change or content quality issues",
    metadata: {},
    createdAt: "2025-11-22T08:00:00Z",
    updatedAt: "2025-11-22T09:00:00Z",
  },
];

// ============================================================================
// CRISIS DETECTION RULES
// ============================================================================

export const mockCrisisDetectionRules: CrisisDetectionRule[] = [
  {
    id: "rule-1",
    workspaceId: "workspace-1",
    name: "Sentiment Spike Detection",
    description: "Alert when negative sentiment exceeds threshold in a short period",
    isActive: true,
    detectionType: "sentiment_spike",
    thresholdConfig: {
      negative_count: 20,
      time_window_minutes: 60,
      platforms: ["twitter", "facebook", "instagram"],
    },
    filterPlatforms: ["twitter", "facebook", "instagram"],
    filterSentiment: ["negative"],
    autoCreateIncident: true,
    notifyUsers: ["user-1", "user-2"],
    notificationChannels: ["email", "slack"],
    priority: 10,
    lastTriggeredAt: "2025-11-22T10:30:00Z",
    triggerCount: 3,
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-11-22T10:30:00Z",
  },
  {
    id: "rule-2",
    workspaceId: "workspace-1",
    name: "Crisis Keywords Monitor",
    description: "Monitor for critical keywords that indicate security or PR crisis",
    isActive: true,
    detectionType: "keyword_match",
    thresholdConfig: {
      keywords: ["data breach", "hack", "lawsuit", "scam", "fraud"],
      case_sensitive: false,
      severity: "critical",
    },
    autoCreateIncident: true,
    notifyUsers: ["user-1", "user-2", "user-3"],
    notificationChannels: ["email", "slack", "sms"],
    priority: 20,
    lastTriggeredAt: "2025-11-20T14:15:00Z",
    triggerCount: 1,
    createdBy: "user-1",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-11-20T14:15:00Z",
  },
  {
    id: "rule-3",
    workspaceId: "workspace-1",
    name: "Message Volume Spike",
    description: "Detect unusual spikes in message volume",
    isActive: true,
    detectionType: "volume_spike",
    thresholdConfig: {
      threshold_multiplier: 3.0,
      time_window_minutes: 30,
      baseline_period_hours: 24,
    },
    autoCreateIncident: true,
    notifyUsers: ["user-1"],
    notificationChannels: ["email", "slack"],
    priority: 5,
    triggerCount: 0,
    createdBy: "user-1",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-02-01T10:00:00Z",
  },
];

// ============================================================================
// STATUS COMPONENTS
// ============================================================================

export const mockStatusComponents: StatusComponent[] = [
  {
    id: "comp-1",
    workspaceId: "workspace-1",
    name: "Instagram Publishing",
    description: "Instagram post publishing and scheduling",
    componentType: "publishing",
    status: "operational",
    displayOrder: 1,
    isVisible: true,
    lastStatusChange: "2025-11-20T12:00:00Z",
    createdBy: "user-1",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-11-20T12:00:00Z",
  },
  {
    id: "comp-2",
    workspaceId: "workspace-1",
    name: "Twitter Inbox",
    description: "Twitter message and mention monitoring",
    componentType: "inbox",
    status: "degraded",
    displayOrder: 2,
    isVisible: true,
    lastStatusChange: "2025-11-22T08:00:00Z",
    lastIncidentAt: "2025-11-22T08:00:00Z",
    createdBy: "user-1",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-11-22T08:00:00Z",
  },
  {
    id: "comp-3",
    workspaceId: "workspace-1",
    name: "Analytics & Reporting",
    description: "Analytics data collection and report generation",
    componentType: "analytics",
    status: "operational",
    displayOrder: 3,
    isVisible: true,
    lastStatusChange: "2025-11-15T09:00:00Z",
    createdBy: "user-1",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-11-15T09:00:00Z",
  },
  {
    id: "comp-4",
    workspaceId: "workspace-1",
    name: "Social Listening",
    description: "Brand mention and keyword monitoring",
    componentType: "listening",
    status: "operational",
    displayOrder: 4,
    isVisible: true,
    lastStatusChange: "2025-11-10T10:00:00Z",
    createdBy: "user-1",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-11-10T10:00:00Z",
  },
  {
    id: "comp-5",
    workspaceId: "workspace-1",
    name: "Facebook Publishing",
    description: "Facebook post publishing and scheduling",
    componentType: "publishing",
    status: "maintenance",
    displayOrder: 5,
    isVisible: true,
    lastStatusChange: "2025-11-22T06:00:00Z",
    createdBy: "user-1",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-11-22T06:00:00Z",
  },
];

// ============================================================================
// STATUS PAGE UPDATES
// ============================================================================

export const mockStatusPageUpdates: StatusPageUpdate[] = [
  {
    id: "update-1",
    workspaceId: "workspace-1",
    componentId: "comp-2",
    incidentId: "incident-1",
    title: "Investigating Negative Sentiment Spike",
    body: "We're currently investigating an unusual spike in negative sentiment on Twitter. Our team is analyzing the situation and will provide updates as we learn more.",
    status: "degraded",
    isPinned: true,
    isPublic: false,
    postedBy: "user-1",
    postedAt: "2025-11-22T10:45:00Z",
    metadata: {},
    createdAt: "2025-11-22T10:45:00Z",
  },
  {
    id: "update-2",
    workspaceId: "workspace-1",
    componentId: "comp-5",
    title: "Scheduled Maintenance - Facebook Integration",
    body: "We're performing scheduled maintenance on our Facebook integration to improve reliability. Facebook post publishing will be temporarily unavailable. Expected completion: 12:00 PM UTC.",
    status: "maintenance",
    isPinned: false,
    isPublic: true,
    postedBy: "user-1",
    postedAt: "2025-11-22T06:00:00Z",
    metadata: {},
    createdAt: "2025-11-22T06:00:00Z",
  },
  {
    id: "update-3",
    workspaceId: "workspace-1",
    incidentId: "incident-2",
    title: "Security Concern Resolved",
    body: "The security-related keywords detected were related to industry news discussion, not our services. We've posted clarifications on all platforms and confirmed there is no security issue affecting our users.",
    status: "operational",
    isPinned: false,
    isPublic: true,
    postedBy: "user-2",
    postedAt: "2025-11-20T18:30:00Z",
    metadata: {},
    createdAt: "2025-11-20T18:30:00Z",
  },
];

// ============================================================================
// MESSAGE SENTIMENT (Sample)
// ============================================================================

export const mockMessageSentiment: MessageSentiment[] = [
  {
    id: "sentiment-1",
    messageId: "msg-1",
    workspaceId: "workspace-1",
    sentiment: "negative",
    score: -0.75,
    confidence: 0.92,
    emotions: {
      anger: 0.6,
      disappointment: 0.3,
      frustration: 0.5,
    },
    keywords: ["delayed", "frustrated", "unacceptable"],
    categories: ["complaint", "shipping"],
    analyzer: "openai",
    modelVersion: "gpt-4o-mini",
    analyzedAt: "2025-11-22T10:31:00Z",
  },
  {
    id: "sentiment-2",
    messageId: "msg-2",
    workspaceId: "workspace-1",
    sentiment: "positive",
    score: 0.85,
    confidence: 0.95,
    emotions: {
      joy: 0.8,
      satisfaction: 0.7,
      excitement: 0.6,
    },
    keywords: ["love", "amazing", "best"],
    categories: ["praise", "product"],
    analyzer: "openai",
    modelVersion: "gpt-4o-mini",
    analyzedAt: "2025-11-22T09:15:00Z",
  },
  {
    id: "sentiment-3",
    messageId: "msg-3",
    workspaceId: "workspace-1",
    sentiment: "neutral",
    score: 0.05,
    confidence: 0.78,
    keywords: ["question", "support", "help"],
    categories: ["inquiry", "support"],
    analyzer: "openai",
    modelVersion: "gpt-4o-mini",
    analyzedAt: "2025-11-22T11:00:00Z",
  },
];
