import type { SocialIdentity } from "../zod-schemas";

export const mockSocialIdentities: SocialIdentity[] = [
  // Sarah Chen - Multi-platform
  {
    id: "identity-1",
    workspace_id: "workspace-1",
    person_id: "person-1",
    social_account_id: "account-1",
    platform: "twitter",
    platform_user_id: "12345",
    platform_username: "sarahchen",
    platform_display_name: "Sarah Chen",
    profile_url: "https://twitter.com/sarahchen",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahChen",
    bio: "Tech entrepreneur and angel investor. Passionate about AI.",
    follower_count: 15200,
    following_count: 890,
    post_count: 1243,
    is_verified: true,
    is_business_account: false,
    first_seen_at: new Date("2024-11-01").toISOString(),
    last_seen_at: new Date().toISOString(),
    last_message_at: new Date().toISOString(),
    platform_data: {},
    created_at: new Date("2024-11-01").toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "identity-2",
    workspace_id: "workspace-1",
    person_id: "person-1",
    social_account_id: "account-2",
    platform: "linkedin",
    platform_user_id: "67890",
    platform_username: "sarah-chen",
    platform_display_name: "Sarah Chen",
    profile_url: "https://linkedin.com/in/sarah-chen",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahChen",
    bio: "CEO at TechVentures Inc | Angel Investor",
    follower_count: 8500,
    following_count: 1200,
    post_count: 342,
    is_verified: false,
    is_business_account: true,
    first_seen_at: new Date("2024-11-01").toISOString(),
    last_seen_at: new Date().toISOString(),
    last_message_at: null,
    platform_data: {},
    created_at: new Date("2024-11-01").toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "identity-3",
    workspace_id: "workspace-1",
    person_id: "person-1",
    social_account_id: "account-3",
    platform: "instagram",
    platform_user_id: "11111",
    platform_username: "sarahchen",
    platform_display_name: "Sarah Chen",
    profile_url: "https://instagram.com/sarahchen",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahChen",
    bio: "✨ Tech & Innovation",
    follower_count: 12300,
    following_count: 450,
    post_count: 234,
    is_verified: true,
    is_business_account: false,
    first_seen_at: new Date("2024-11-05").toISOString(),
    last_seen_at: new Date(Date.now() - 3600000).toISOString(),
    last_message_at: null,
    platform_data: {},
    created_at: new Date("2024-11-05").toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },

  // John Doe
  {
    id: "identity-4",
    workspace_id: "workspace-1",
    person_id: "person-2",
    social_account_id: "account-4",
    platform: "whatsapp",
    platform_user_id: "+15550102",
    platform_username: null,
    platform_display_name: "John Doe",
    profile_url: null,
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=JohnDoe",
    bio: null,
    follower_count: null,
    following_count: null,
    post_count: null,
    is_verified: false,
    is_business_account: false,
    first_seen_at: new Date("2024-11-15").toISOString(),
    last_seen_at: new Date(Date.now() - 3600000).toISOString(),
    last_message_at: new Date(Date.now() - 3600000).toISOString(),
    platform_data: {},
    created_at: new Date("2024-11-15").toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "identity-5",
    workspace_id: "workspace-1",
    person_id: "person-2",
    social_account_id: "account-5",
    platform: "facebook",
    platform_user_id: "22222",
    platform_username: "john.doe",
    platform_display_name: "John Doe",
    profile_url: "https://facebook.com/john.doe",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=JohnDoe",
    bio: "Marketing professional",
    follower_count: 543,
    following_count: 321,
    post_count: 89,
    is_verified: false,
    is_business_account: false,
    first_seen_at: new Date("2024-11-15").toISOString(),
    last_seen_at: new Date("2024-12-15").toISOString(),
    last_message_at: null,
    platform_data: {},
    created_at: new Date("2024-11-15").toISOString(),
    updated_at: new Date("2024-12-15").toISOString(),
  },

  // Emily Rodriguez
  {
    id: "identity-6",
    workspace_id: "workspace-1",
    person_id: "person-3",
    social_account_id: "account-6",
    platform: "instagram",
    platform_user_id: "33333",
    platform_username: "emilyrodriguez",
    platform_display_name: "Emily Rodriguez",
    profile_url: "https://instagram.com/emilyrodriguez",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=EmilyRodriguez",
    bio: "Content creator | Fashion & Lifestyle 👗✨",
    follower_count: 45600,
    following_count: 1200,
    post_count: 892,
    is_verified: true,
    is_business_account: true,
    first_seen_at: new Date("2024-10-20").toISOString(),
    last_seen_at: new Date(Date.now() - 7200000).toISOString(),
    last_message_at: new Date(Date.now() - 7200000).toISOString(),
    platform_data: {},
    created_at: new Date("2024-10-20").toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "identity-7",
    workspace_id: "workspace-1",
    person_id: "person-3",
    social_account_id: "account-7",
    platform: "tiktok",
    platform_user_id: "44444",
    platform_username: "emily.rodriguez",
    platform_display_name: "Emily Rodriguez",
    profile_url: "https://tiktok.com/@emily.rodriguez",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=EmilyRodriguez",
    bio: "Fashion & Lifestyle ✨",
    follower_count: 128000,
    following_count: 234,
    post_count: 456,
    is_verified: true,
    is_business_account: false,
    first_seen_at: new Date("2024-10-25").toISOString(),
    last_seen_at: new Date(Date.now() - 10800000).toISOString(),
    last_message_at: null,
    platform_data: {},
    created_at: new Date("2024-10-25").toISOString(),
    updated_at: new Date(Date.now() - 10800000).toISOString(),
  },

  // Michael Brown
  {
    id: "identity-8",
    workspace_id: "workspace-1",
    person_id: "person-4",
    social_account_id: "account-8",
    platform: "linkedin",
    platform_user_id: "55555",
    platform_username: "michael-brown",
    platform_display_name: "Michael Brown",
    profile_url: "https://linkedin.com/in/michael-brown",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=MichaelBrown",
    bio: "VP of Sales at Enterprise Solutions Corp",
    follower_count: 3200,
    following_count: 890,
    post_count: 123,
    is_verified: false,
    is_business_account: true,
    first_seen_at: new Date("2024-09-10").toISOString(),
    last_seen_at: new Date("2024-12-15").toISOString(),
    last_message_at: new Date("2024-12-15").toISOString(),
    platform_data: {},
    created_at: new Date("2024-09-10").toISOString(),
    updated_at: new Date("2024-12-15").toISOString(),
  },

  // Jessica Taylor
  {
    id: "identity-9",
    workspace_id: "workspace-1",
    person_id: "person-5",
    social_account_id: "account-9",
    platform: "twitter",
    platform_user_id: "66666",
    platform_username: "jesstaylor",
    platform_display_name: "Jess",
    profile_url: "https://twitter.com/jesstaylor",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=JessicaTaylor",
    bio: "Just here for the memes",
    follower_count: 234,
    following_count: 456,
    post_count: 1892,
    is_verified: false,
    is_business_account: false,
    first_seen_at: new Date(Date.now() - 86400000).toISOString(),
    last_seen_at: new Date(Date.now() - 86400000).toISOString(),
    last_message_at: new Date(Date.now() - 86400000).toISOString(),
    platform_data: {},
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "identity-10",
    workspace_id: "workspace-1",
    person_id: "person-5",
    social_account_id: "account-10",
    platform: "discord",
    platform_user_id: "77777",
    platform_username: "jesstaylor#1234",
    platform_display_name: "Jess",
    profile_url: null,
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=JessicaTaylor",
    bio: null,
    follower_count: null,
    following_count: null,
    post_count: null,
    is_verified: false,
    is_business_account: false,
    first_seen_at: new Date(Date.now() - 86400000).toISOString(),
    last_seen_at: new Date(Date.now() - 86400000).toISOString(),
    last_message_at: null,
    platform_data: {},
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },

  // David Kim
  {
    id: "identity-11",
    workspace_id: "workspace-1",
    person_id: "person-6",
    social_account_id: "account-11",
    platform: "instagram",
    platform_user_id: "88888",
    platform_username: "davidkim",
    platform_display_name: "David Kim",
    profile_url: "https://instagram.com/davidkim",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidKim",
    bio: "🎥 Content Creator | 500K+ Followers",
    follower_count: 523000,
    following_count: 890,
    post_count: 1234,
    is_verified: true,
    is_business_account: true,
    first_seen_at: new Date("2024-11-20").toISOString(),
    last_seen_at: new Date(Date.now() - 172800000).toISOString(),
    last_message_at: new Date(Date.now() - 172800000).toISOString(),
    platform_data: {},
    created_at: new Date("2024-11-20").toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "identity-12",
    workspace_id: "workspace-1",
    person_id: "person-6",
    social_account_id: "account-12",
    platform: "youtube",
    platform_user_id: "99999",
    platform_username: "davidkim",
    platform_display_name: "David Kim",
    profile_url: "https://youtube.com/@davidkim",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidKim",
    bio: "Content Creator & Filmmaker",
    follower_count: 245000,
    following_count: 123,
    post_count: 342,
    is_verified: true,
    is_business_account: false,
    first_seen_at: new Date("2024-11-20").toISOString(),
    last_seen_at: new Date(Date.now() - 259200000).toISOString(),
    last_message_at: null,
    platform_data: {},
    created_at: new Date("2024-11-20").toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "identity-13",
    workspace_id: "workspace-1",
    person_id: "person-6",
    social_account_id: "account-13",
    platform: "twitter",
    platform_user_id: "10101",
    platform_username: "davidkim",
    platform_display_name: "David Kim",
    profile_url: "https://twitter.com/davidkim",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidKim",
    bio: "🎥 Content Creator",
    follower_count: 89000,
    following_count: 567,
    post_count: 2341,
    is_verified: true,
    is_business_account: false,
    first_seen_at: new Date("2024-11-20").toISOString(),
    last_seen_at: new Date(Date.now() - 345600000).toISOString(),
    last_message_at: null,
    platform_data: {},
    created_at: new Date("2024-11-20").toISOString(),
    updated_at: new Date(Date.now() - 345600000).toISOString(),
  },

  // Spam User
  {
    id: "identity-14",
    workspace_id: "workspace-1",
    person_id: "person-7",
    social_account_id: "account-14",
    platform: "slack",
    platform_user_id: "11223",
    platform_username: "spamuser",
    platform_display_name: "Spam User",
    profile_url: null,
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=SpamUser",
    bio: null,
    follower_count: null,
    following_count: null,
    post_count: null,
    is_verified: false,
    is_business_account: false,
    first_seen_at: new Date(Date.now() - 604800000).toISOString(),
    last_seen_at: new Date(Date.now() - 604800000).toISOString(),
    last_message_at: new Date(Date.now() - 604800000).toISOString(),
    platform_data: {},
    created_at: new Date(Date.now() - 604800000).toISOString(),
    updated_at: new Date(Date.now() - 604800000).toISOString(),
  },

  // Robert Martinez
  {
    id: "identity-15",
    workspace_id: "workspace-1",
    person_id: "person-8",
    social_account_id: "account-15",
    platform: "telegram",
    platform_user_id: "12345678",
    platform_username: "robertmartinez",
    platform_display_name: "Robert",
    profile_url: null,
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=RobertMartinez",
    bio: null,
    follower_count: null,
    following_count: null,
    post_count: null,
    is_verified: false,
    is_business_account: false,
    first_seen_at: new Date(Date.now() - 3600000).toISOString(),
    last_seen_at: new Date(Date.now() - 3600000).toISOString(),
    last_message_at: new Date(Date.now() - 3600000).toISOString(),
    platform_data: {},
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
];
